### ISSUE TITLE
The requested accessory '" + name + "' was not registered by any plugin

### ISSUE THREAD

**Issue by Nastras** [nicoh88/homebridge-xiaomi-roborock-vacuum#1]
Guten Morgen,

habe vorhin dein Plugin entdeckt und wollte es direkt mal ausprobieren. Leider erhalte ich diesen standard Fehler beim starten der Homebridge Instanz.

Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] ERROR LOADING PLUGIN homebridge-xiaomi-mi-robot-vacuum:
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] Error: Cannot find module 'miio'
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module._resolveFilename (module.js:543:15)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module._load (module.js:470:25)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module.require (module.js:593:17)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at require (internal/module.js:11:18)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-mi-robot-vacuum/index.js:1:74)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module._compile (module.js:649:30)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.Module._extensions..js (module.js:660:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module.load (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at tryModuleLoad (module.js:501:12)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module._load (module.js:493:3)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module.require (module.js:593:17)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at require (internal/module.js:11:18)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:22)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:142:14)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Array.forEach (<anonymous>:null:null)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:24)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module._compile (module.js:649:30)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.Module._extensions..js (module.js:660:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module.load (module.js:561:32)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at tryModuleLoad (module.js:501:12)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module._load (module.js:493:3)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module.runMain (module.js:690:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at startup (bootstrap_node.js:194:16)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at bootstrap_node.js:666:3
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] ====================
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] Loaded config.json with 1 accessories and 0 platforms.
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] ---
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] Loading 0 platforms...
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: [2018-3-23 08:30:55] Loading 1 accessories...
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: /usr/lib/node_modules/homebridge/lib/api.js:64
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:       ^
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]: Error: The requested accessory 'XiaomiRoborockVacuum' was not registered by any plugin.
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module._compile (module.js:649:30)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Object.Module._extensions..js (module.js:660:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Module.load (module.js:561:32)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at tryModuleLoad (module.js:501:12)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module._load (module.js:493:3)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at Function.Module.runMain (module.js:690:10)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at startup (bootstrap_node.js:194:16)
Mär 23 08:30:55 HomeBridgeServer homebridge[23811]:     at bootstrap_node.js:666:3
Mär 23 08:30:55 HomeBridgeServer systemd[1]: homebridge-test.service: Main process exited, code=exited, status=1/FAILURE
Mär 23 08:30:55 HomeBridgeServer systemd[1]: homebridge-test.service: Unit entered failed state.
Mär 23 08:30:55 HomeBridgeServer systemd[1]: homebridge-test.service: Failed with result 'exit-code'.
^C

Ich habe es als root installiert und zusätzlich die schreibrechte umgangen mit:
sudo npm install -g --unsafe-perm homebridge-xiaomi-roborock-vacuum -g

Die Installation war auch erfolgreich ohne Fehler:

root@HomeBridgeServer:/home/pi# sudo npm install -g --unsafe-perm homebridge-xiaomi-mi-robot-vacuum -g
+ homebridge-xiaomi-mi-robot-vacuum@1.2.0
updated 1 package in 0.977s

root@HomeBridgeServer:/home/pi# sudo npm list -g --depth=0
/usr/lib
├── homebridge@0.4.38
├── homebridge-automation-calendar@0.0.2
├── homebridge-automation-switches@3.2.1
├── homebridge-broadlink-rm@3.3.6
├── homebridge-calendar@0.3.0
├── homebridge-callmonitor@0.0.3
├── homebridge-eveatmo@0.3.3
├── homebridge-fritz@0.6.0
├── homebridge-harmonyhub@0.3.0-alpha.2
├── homebridge-hue@0.8.7
├── homebridge-ifttt@0.3.0
├── homebridge-mi-fan@0.0.5
├── homebridge-mi-flower-care@1.0.7
├── homebridge-mi-robot_vacuum@0.1.2
├── homebridge-people@0.6.2
├── homebridge-platform-wemo@1.3.6
├── homebridge-soundtouch@5.2.0
├── homebridge-tado-thermostat-plugin@3.1.6
├── homebridge-telegram@0.2.0
├── homebridge-weather-station-extended@1.2.3
├── homebridge-xiaomi-mi-robot-vacuum@1.2.0
├── n@2.1.8
└── npm@5.7.1

Anschließend habe ich noch einen npm rebuild durchgeführt in der Hoffnung das es dadurch behoben wird, leider auch ohne Erfolg.

Hast du eine Idee wo das Problem sein könnte?

Ps: In deiner Beispiel Config ist ein kleiner Fehler, bei der ersten }, Klammer ist das Komma zu viel:

  "dock": true
 },
],

Gruß Nastra

**Comment by nicoh88** [comment]
Habe ein Fehler in der Doku ...

`npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm`

... ist der richtige Befehl zum Installieren.

**Comment by Nastras** [comment]
Hey, jetzt funktioniert alles, da hätte ich ja noch lange ausprobieren können wenn ich das Falsche Paket geldüaden habe.

Super gemacht das Plugin, ich steige um👍

Habe im SmartApfel Forum schon ein entsprechenden Info Thread heute Morgen zum Plugin aufgemacht.

Noch eine Frage siehst du eventuell die Möglichkeit die Verschleißanzeige für Bürsten und Filter mit einzublenden. Hatte das schonmal im FHEM Forum gesehen bin mir aber nicht sicher ob man das hier auch realisieren könnte?

**Comment by nicoh88** [comment]
@Nastras 
Das freut mich. 👍 

Ja, die Werte bekomme ich vom Roboter, theoretisch sollte es also funktionieren. 

```
mainBrushWorkTime: 160934
sideBrushWorkTime: 160934
```

Aber ich wüsste nicht als welchen Gerätetyp ich das anzeigen lassen soll. Du kannst dir ja mal Gedanken machen, wie du es dir vorstellst und welcher Gerätetyp es sein soll. Wenn du alle Infos und Vorstellungen zusammen hast, machst du einfach ein neues Issue auf.



Gruß Nico
