### ISSUE TITLE
Update error!

### ISSUE THREAD

**Issue by JuvenRui** [nicoh88/homebridge-xiaomi-roborock-vacuum#10]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/nicoh88/miio.git
npm ERR!
npm ERR! fatal: failed to stat '.': Permission denied
npm ERR!
npm ERR! exited with error code: 128

**Comment by JuvenRui** [comment]
sudo npm uninstall -g homebridge-xiaomi-roborock-vacuum
npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm

And install error.

**Comment by nicoh88** [comment]
@JuvenRui „git“ is installed?

**Comment by JuvenRui** [comment]
Install miio version is 0.14.1, but not upgrade it. This may be the reason.....
