### ISSUE TITLE
Log entries issue on version 0.6.8

### ISSUE THREAD

**Issue by costispavlou** [nicoh88/homebridge-xiaomi-roborock-vacuum#109]
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:20:34] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:34] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:26:01] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:26:01] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:26:02] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:26:02] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%

version 0.6.8

**Comment by afharo** [comment]
Can you please explain what the issue is about?

Please, mind the comment https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/94#issuecomment-586634108

**Comment by costispavlou** [comment]
replied to your comment. thank you.
