### ISSUE TITLE
Einen vorher konfigurierten Bereich abfahren.

### ISSUE THREAD

**Issue by ThomasBoettner** [nicoh88/homebridge-xiaomi-roborock-vacuum#11]
Hallo,
gibt es die Möglichkeit über Miio vorher eine Karte für meine Wohnung zu erstellen, so dass nur diese beim reinigen abgefahren wird?
Letztendlich genau wie im App nur dass diese nur einmal eingestellt werden müsste.

**Comment by nicoh88** [comment]
Leider nein. 👎
