### ISSUE TITLE
Room cleaning Feature

### ISSUE THREAD

**Issue by diwiesign** [nicoh88/homebridge-xiaomi-roborock-vacuum#114]
Thank you very much for realizing the new room features!

Unfortunately I currently have the problem that homebridge crashes when I write the room definitions into the JSON.

```
        {
            "accessory": "XiaomiRoborockVacuum",
            "name": "Staubsauger",
            "ip": "192.168.178.xx",
            "token": "blablabla",
            "waterBox": false,
            "pause": true,
            "dock": true,
	    "cleanword": "cleaning",
	    "rooms": [
				{
				"id": 1,
				"name": "Wohnzimmer"
				},
				{
				"id": 2,
				"name": "Flur"
				}
	    ]
        }
```

I'm definitely doing something wrong. ;)

```
[2/26/2020, 13:19:35] [Staubsauger] Initializing XiaomiRoborockVacuum accessory...
[2/26/2020, 13:19:35] [Staubsauger] INF createRoom | undefined | Room Wohnzimmer (1)
[2/26/2020, 13:19:35] [Staubsauger] INF createRoom | undefined | Room Flur (2)
[2/26/2020, 13:19:35] TypeError: Cannot read property 'toString' of undefined
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:154:59)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:471:19
    at Array.forEach (<anonymous>)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:451:14)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[2/26/2020, 13:19:35] Got SIGTERM, shutting down Homebridge...
```

**Comment by netRunner0** [comment]
![IMG_0528](https://user-images.githubusercontent.com/44049295/75348074-f3c71900-58c3-11ea-9678-ea3438982dc9.png)
![IMG_0529](https://user-images.githubusercontent.com/44049295/75348086-faee2700-58c3-11ea-89d1-d3515129db79.png)

**Comment by misanthrophy** [comment]
Same error as @diwiesign on my Xiaomi Roborock S50 when I enable rooms. (Where do I get the ID of the rooms, or can I use my own numbers? And where do I set the setting, that my robo knows which room in the config, is which physical room in my apartment?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
@diwiesign : strange, i can't reproduce it ...

@netRunner0 : can you try with "id" instead of "ID" ... 

@misanthrophy : you have to get them out of your bot.  (you can do with iobroker) ... i will think about an option direct into the plugin. 

You can try installing the plugin from my develop branche (https://github.com/c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum/tree/develop) and activate the autoroom feature. then take a look into the Log

**Comment by afharo** [comment]
@diwiesign I think the key point here is the `undefined` in 
```
[2/26/2020, 13:19:35] [Staubsauger] INF createRoom | undefined | Room Wohnzimmer (1)
```

In there it's supposed to log the model and it looks like it's not recognised for some reason...

**Comment by afharo** [comment]
Actually, scratch that! At that point, it's quite likely we won't have the model yet.
I'll push an update! It's related to the Pause switch. It should have a subtype.

**Comment by afharo** [comment]
PR created for that change :)

**Comment by terriblefox** [comment]
I got this message:
[2/26/2020, 8:58:19 PM] [Xiaomi Mi Robot] ERR getRoomMap | No vacuum cleaner is discovered yet.
[2/26/2020, 8:58:19 PM] [Xiaomi Mi Robot] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device

think its the same issue

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes and no ... you are now on my dev branch right? there is the try of auto room mapping.
this function isn't in the stable version.

i reactivate in dev only for getting the IDs

**Comment by netRunner0** [comment]
@c-o-m-m-a-n-d-e-r 
![696E99AE-2DB6-4BC3-AA03-7B5024F92D9C](https://user-images.githubusercontent.com/44049295/75413703-1ac72e80-5948-11ea-9697-1486598d72ed.png)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
now you have the other problem, but PR for this is already made.

will be solved very soon

**Comment by diwiesign** [comment]
> @misanthrophy : you have to get them out of your bot. (you can do with iobroker) ... i will think about an option direct into the plugin.
> 
> You can try installing the plugin from my develop branche (https://github.com/c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum/tree/develop) and activate the autoroom feature. then take a look into the Log

Thank you! How can I install this develop branche? I try

`npm install --save https://github.com/c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum.git
`

but I get

```
npm WARN saveError ENOENT: no such file or directory, open '/var/homebridge/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/homebridge/package.json'
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No README data
npm WARN homebridge No license field.

+ homebridge-xiaomi-roborock-vacuum@0.6.9-dev
updated 1 package and audited 1149 packages in 11.567s

13 packages are looking for funding
  run `npm fund` for details

found 5 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

with log

```
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'audit' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose npm-session baf8d5f5d50fd04e
5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/audit.js:164:19
5 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:514:35)
5 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
5 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
5 verbose stack     at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
5 verbose stack     at PromiseArray._iterate (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
5 verbose stack     at PromiseArray.init [as _init] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
5 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
5 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose cwd /var/homebridge
7 verbose Linux 4.19.97-v7+
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit"
9 verbose node v12.16.1
10 verbose npm  v6.13.4
11 error code EAUDITNOPJSON
12 error audit No package.json found: Cannot audit a project without a package.json
13 verbose exit [ 1, true ]
```

**Comment by netRunner0** [comment]
Can I make sure that the switch for the wedge remains active while the room is being cleaned?
And you also need to separate them so that you can spread them into rooms.

Thanks for the work!

**Comment by c-o-m-m-a-n-d-e-r** [comment]
@diwiesign : try 

npm install --save c-o-m-m-a-n-d-e-r/homebridge-xiaomi-roborock-vacuum#840388a3df61df0e3c3581eb7279bce910313f76

but i think stable update will release very soon.

@netRunner0 : not sure what you mean with "wedge" :-)

**Comment by netRunner0** [comment]
@c-o-m-m-a-n-d-e-r rooms)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
ahh yes i saw this also ... not sure why this sometimes happen. will debug this

**Comment by nicoh88** [comment]
@netRunner0 

If exist 

> Can I make sure that the switch for the rooms remains active while the room is being cleaned?
> And you also need to separate them so that you can spread them into rooms.
> 
> Thanks for the work!

Please new issue. Thanks

**Comment by serbasan** [comment]
> @misanthrophy : you have to get them out of your bot. (you can do with iobroker) ... i will think about an option direct into the plugin.

Hi. Also tego Xiaomi Roborock S50. I have installed ibroker on a laptop. How could you see the room IDs? I need help. In the homebridge log I don't see any of that.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
sorry not working with an S50 ... you have to get them by hand ... start with 16 and then up ... if you didn't have all rooms try lower values.

Its by design ... sorry

**Comment by serbasan** [comment]
Perfect, I am sending to room id and with the Mihome application I see which room you are going to. Thank you
