### ISSUE TITLE
On stop didn‘t going back to the Dock S6

### ISSUE THREAD

**Issue by Tim2309** [nicoh88/homebridge-xiaomi-roborock-vacuum#116]
Hi,
With 0.7 I still got the problem #106 
If i change the percentage to 0% it says spot cleaning and stop

**Comment by afharo** [comment]
@c-o-m-m-a-n-d-e-r any idea? 🤔

**Comment by c-o-m-m-a-n-d-e-r** [comment]
mhhh not sure was is exactly the problem.
what do  you want? when you set it to 0% you wanna go back to dock?

in my changes i only changed the behavior of the rooms.

@Tim2309 : can you tell me exactly your steps to reproduce it please? (overall cleaning? room cleaning? etc.)

then i can take a look at it

**Comment by afharo** [comment]
I thought you had the S6 as well :)

In your changes, we changed the stop behaviour. It now calls `app_charge` straight away without calling `app_stop` first

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes i have :-) but i only changed in the room cleaning function.

i think he is using overall cleaning. this is another function.
i will fix this atm.

**Comment by Tim2309** [comment]
My config is very basic:
"name": "Staubsauger",
            "ip": "192.168.1.8",
            "token",
            "waterBox": false,
            "pause": true,
            "dock": false,
            "accessory": "XiaomiRoborockVacuum"
 
if I set it to any percentage, for example 50% the robot start cleaning.
After 20sec i set it to 0% (off) the robot says: „spot cleaning“ and stop at this position.
If i pause it (with the switch) before and then set 0% it is going back to the dock.

**Comment by afharo** [comment]
Are you running the latest firmware? I recall there was some issue with the S6 model that got resolved after a firmware upgrade 🤔

**Comment by Tim2309** [comment]
3.5.4_1048 got this new firmware 1 or 2 days ago

**Comment by afharo** [comment]
And still no luck? 😞

**Comment by c-o-m-m-a-n-d-e-r** [comment]
i'm on latest too .... will report tomorrow

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Strange, can't confirm this.

I started the Robo with raise the fan speed ... let him drive a few meters then lower the fan speed to 0. Bot stops and say : driving through station ... and then going back to dock.

works as expected ...

**Comment by Tim2309** [comment]
I tried to restart the complete homebridge container on my synology, now it‘s going back to the dock.
I think there was something left in the cache of the server.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
glad to here ...
