### ISSUE TITLE
Error Codes im Journalctl entschlüsseln

### ISSUE THREAD

**Issue by Nastras** [nicoh88/homebridge-xiaomi-roborock-vacuum#12]
Hallo @nicoh88 

ich habe heute das erstmal seit dem ich dein Plugin nutze von einem meiner Sauger im Journalctl einen Fehler ausgeworfen bekommen da er ein Problem beim Reinigungsvorgang hat.

Mai 03 10:20:21 HomeBridgeServer homebridge[2653]: Code { id: 2, description: 'Unknown error 2' }
Mai 03 10:20:21 HomeBridgeServer homebridge[2653]: [2018-5-3 10:20:21] [Sauger Garage] MONITOR | CleaningState has changed, is now false
Mai 03 10:20:21 HomeBridgeServer homebridge[2653]: [2018-5-3 10:20:21] [Sauger Garage] INFO | Cleaning was stopped.

Im Journalctl ist mit dem Fehler Code so wie er jetzt erscheint, leider nichts anzufangen. Ist es möglich das du diese gemäß der angehängten Tabelle entschlüsselst bzw. ausgibt?

[Fehlercodes.pdf](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/files/1970114/Fehlercodes.pdf)

Gruß Nastra

**Comment by nicoh88** [comment]
Erledigt. 😄 

https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/commit/0aff58896c14ecc2819e014e23bf81b2e208713a

**Comment by Nastras** [comment]
Super, danke dir!
