### ISSUE TITLE
Cleaning all and rooms

### ISSUE THREAD

**Issue by suxus-zz** [nicoh88/homebridge-xiaomi-roborock-vacuum#123]
Hello 

I want have in the HomeKit App 

one switch to cleaning all rooms
one switch to cleaning the livingroom
one switch to cleaning the kitchen

Is this with this config possible?

`
"accessories": [
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Cleaning All",
  "ip": "192.168.1.150",
  "token": "abcdef1234567890abcdef1234567890",
  "pause": false,
  "dock": true,
  "waterBox": false,
  "cleanword": "cleaning",
 },
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Cleaning Livingroom",
  "ip": "192.168.1.150",
  "token": "abcdef1234567890abcdef1234567890",
  "pause": false,
  "dock": true,
  "waterBox": false,
  "cleanword": "cleaning",
  "rooms": [
    {
      "id": 1,
      "name": "Livingroom"
    }
  ]
 },
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Cleaning Kitchen",
  "ip": "192.168.1.150",
  "token": "abcdef1234567890abcdef1234567890",
  "pause": false,
  "dock": true,
  "waterBox": false,
  "cleanword": "cleaning",
  "rooms": [
    {
      "id": 2,
      "name": "Kitchen"
    }
  ]
 } 
]
`

Is the id a consecutive number that i can choose? And name is the name from the Xiaomi app for the corresponding room?

Thank you very much for this great feature.

Greeting

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Yes, this is possible, but your can't choose ID yourself.
What Model do you have?

ID have to be the ID from the Robo (most start with 16) ... Naming is for the App right.

If you have an S6 you can add "autoroom" : true in your config an then look at the log file.

**Comment by suxus-zz** [comment]
Thank you very much for the answer.

Yes i have a S6.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Yes, then please try "autoroom" : true in your config and take a look into the Log, there you will find your Room IDs

**Comment by suxus-zz** [comment]
Great thank you very much

**Comment by suxus-zz** [comment]
First this

"accessories": [
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Cleaning All",
  "ip": "192.168.1.150",
  "token": "abcdef1234567890abcdef1234567890",
  "pause": false,
  "dock": true,
  "waterBox": false,
  "cleanword": "cleaning",
  "autoroom": true
 }
]

and then i will check the log and after that i can create the other switch with the right id and name. And so i have a switch to cleaning all rooms and then i have switches for each room in the Home App.

**Comment by suxus-zz** [comment]
Hello

I have edit my config to this

`
"accessories": [
 {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Cleaning All",
  "ip": "192.168.9.110",
  "token": "abcd...",
  "pause": false,
  "dock": true,
  "cleanword": "cleaning",
  "autoroom": true
 }
]
`
After that i reboot my Homebridge but i can't see no id or name in the log.
Is this not the right settings?
Greeting

**Comment by c-o-m-m-a-n-d-e-r** [comment]
search fro getRoomMap in the Log ... its only one line.

your config looks correct for me

**Comment by suxus-zz** [comment]
Yes i find it, it call
Map is 21,766001007255,16,766001007249,17,766001007251,18,766001007252,19,766001007253,20,766001007254

What is here the id and name?
Greeting

**Comment by c-o-m-m-a-n-d-e-r** [comment]
16,17,18,19,20,21 are your IDs.

as example : 16,766001007249 - the part after the comma is the internal name (the names dosn't come via the api). now you have to configure your rooms and test them one by one and then updte config with right names.

**Comment by suxus-zz** [comment]
Great, thank you very much, i will try with the rooms.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
@suxus-zz : working?

**Comment by suxus-zz** [comment]
I just got home and just tested the first room. Now has to find out which ID has which room.

What is the idea of cleanword?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
cleanword is used to create the switches ...

as example in german i use "sauge" (clean) and then with the room name the switch ist called: sauge Wohnzimmer (clean Livingroom) ... so you can direct use with Siri as example

**Comment by suxus-zz** [comment]
Ahhh i understand i'm also from germany

"cleanword": "sauge
"rooms": [
                {
                    "id": 16,
                    "name": "Wohnzimmer"

for Siri "sauge Wohnzimmer"

**Comment by c-o-m-m-a-n-d-e-r** [comment]
exactly ... genau ;-)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
can we close this issue ?

**Comment by suxus-zz** [comment]
Yes, thank you
