### ISSUE TITLE
S5 Room IDs

### ISSUE THREAD

**Issue by pax0707** [nicoh88/homebridge-xiaomi-roborock-vacuum#129]
Does anyone know what the ID range is for s5 model?
Tried 1-36 and nothing.
Or how can I get them, the log doesn't show anything about that.

**Comment by afharo** [comment]
I think you need the latest firmware for the S5 model to support rooms.
I finally got the update myself (after hearing some folks already using it from weeks ago)
![694A373F-5480-4D42-A5D7-24AEADB7E648](https://user-images.githubusercontent.com/5469006/75825891-398d5100-5d9e-11ea-89ca-b692a54b9a9d.png)

I guess it’s a matter of time 😉

**Comment by pax0707** [comment]
I've been running 2008 for some time now.

**Comment by luc-ass** [comment]
I was actually able to configure rooms, just not all of them. It worked for IDs 16-20 but no more. Really strange. For all the other rooms my S5 tells me, that it can not reach the room.

```
 "rooms": [
                {
                    "name": "Wohnzimmer",
                    "id": 17
                },
                {
                    "name": "Esszimmer",
                    "id": 16
                },
                {
                    "name": "Flur",
                    "id": 18
                },
                {
                    "name": "Schlafzimmer",
                    "id": 19
                },
                {
                    "name": "Küche",
                    "id": 20
                },
```
Is there a patch for this?

Model: Roborock S5
Firmware: 3.5.7_002008

**Comment by pax0707** [comment]
I get that for all rooms...

**Comment by luc-ass** [comment]
Never mind - somehow my roomIDs are 1, 5, 16, 17, 18, 19, 20...
where is the logic in that?!

**Comment by luc-ass** [comment]
Wich numbers did you try?

**Comment by pax0707** [comment]
1-36.
Didn't go further but looks like I will have to.

**Comment by JonoHaysom** [comment]
any ideas how we can get the room IDs to list?

**Comment by afharo** [comment]
Try using the autoroom option. In the readme file it’s detailed how it works :)

**Comment by luc-ass** [comment]
That did not work with my S5. I had to „brut force” it.

**Comment by afharo** [comment]
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/#semi-automatic should work now for any version :)
