### ISSUE TITLE
Nach 1. Benutzung 'handshake timeout'

### ISSUE THREAD

**Issue by Scream4Life** [nicoh88/homebridge-xiaomi-roborock-vacuum#13]
Hi, ich hab das Plugin auf meinem Pi3 laufen (NPM 6.0, Node 8.11.1, Plugin 0.3). Nach der Installation als root und Aufnahme in der Config war die Anzeige in der Home und EVE App erfolgreich. Auch ein erstes Starten und bewegen des Sliders liefen problemlos. Allerdings ließ sich der Sauger (v1) nicht mehr stoppen. Ich habe dann den Button an der Oberseite gedrückt um ihn auszuschalten. Jetzt bekomme ich nach dem Start der Homebridge nur noch diese Fehler und kann den Sauger nicht mehr ansprechen.

[2018-5-9 22:50:11] [Staubi] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-5-9 22:52:13] [Staubi] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-5-9 22:54:15] [Staubi] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-5-9 22:56:17] [Staubi] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-5-9 22:58:19] [Staubi] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-5-9 23:00:10] [Staubi] ERROR, getCleaning | No vacuum cleaner is discovered.
[2018-5-9 23:00:10] [Staubi] ERROR, getCleaning | No vacuum cleaner is discovered.
[2018-5-9 23:00:10] [Staubi] ERROR, getBatteryLow | No vacuum cleaner is discovered.
[2018-5-9 23:00:10] [Staubi] ERROR, getDocked | No vacuum cleaner is discovered.

Any idea?

**Comment by chstoll** [comment]
Hallo,

ich habe ein ähnliches Problem. Habe auch das PlugIn 0.3 auf nem Pi3 laufen. Bei mir funktioniert die Kommunikation mit dem Sauger nach dem Start der Homebridge für vielleicht 2-3 Stunden, dann bricht die Verbindung scheinbar ab. Es gibt im allerdings keine Fehlermeldung im Log, aber weder die Steuerung über die Home-App noch die Stati (z. B. Dock) werden aktualisiert. Nach dem Restart der Homebridge funktioniert es dann wieder eine gewisse Zeit.

**Comment by nicoh88** [comment]
Wie häufig tritt das Problem bei euch auf?

**Comment by Scream4Life** [comment]
Also bei mir war das Plugin nur am Anfang kurz benutzbar. Danach habe ich nur diese Fehlermeldungen erhalten und habe es wieder abgeschaltet, bis eine Lösung erkennbar ist. Diverse Reboots von Homebridge, Pi und Staubsauger hatte ich bereits durchgeführt.

**Comment by nicoh88** [comment]
@Scream4Life Ist der Token noch korrekt oder hat dieser sich geändert? Wenn du nun Homebridge mit meinem Plugin startest, kommen was für Fehlermeldungen?

Gruß Nico

**Comment by Scream4Life** [comment]
Hmm, vielleicht lag hier ein anderes Netzwerk-Problem vor?! Ich habe das Plugin gerade wieder in der Config aufgenommen und nichts geändert. Es jetzt mehrfach ohne Probleme funktioniert und der Status' wird ebenfalls überall korrekt angezeigt. 

Vielleicht nochmal eine generelle Frage: Sollte ich von Firmware Updates des Saugers in Zukunft abstand nehmen bzw. erstmal Deine Updatehistorie prüfen?

**Comment by chstoll** [comment]
Also bei mir verhält es sich anders. Die Stati werden einfach nicht korrekt aktualisiert. Aktuell zeigt der Sauger an, er würde mit 90% saugen und die Dockingstation hat nicht ausgelöst:

May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Pause possible true.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Cleaning is true.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Fanspeed is 90%.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Docked is false.

Das ist aber nicht der Fall. Der Sauger steht auf der Dockingstation und ist nicht wirklich am saugen :-)
Starte ich homebridge neu, passt es wieder:

May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Pause possible false.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Fanspeed is 90%.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Cleaning is false.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Docked is true.

Meist wird schon nach dem ersten Saugvorgang das ganze nicht mehr richtig aktualisiert.

**Comment by nicoh88** [comment]
@chstoll 

Komisch. Hast du die aktuellste Version installiert?

`npm -g list --depth=0 | grep -i homebridge-xiaomi-roborock-vacuum`

**Comment by chstoll** [comment]
Ja, Version passt:

`├── homebridge-xiaomi-roborock-vacuum@0.3.0`

Ist schon seltsam, es kommt ja auch keine Fehlermeldung im Log. Gibt es da noch erweitertes Logging, was ich aktivieren könnte?

**Comment by nicoh88** [comment]
@chstoll Ja, starte mal homebridge zusätzlich mit "**-D**".

**Comment by maikburd** [comment]
Dieses Verhalten muss ich auch leider beobachten. Sauger ist im Dock, aber in HK wir mir noch Aktivität angezeigt.

**Comment by Luftloch80** [comment]
Bei mir das selbe verhalten

**Comment by nicoh88** [comment]
Da in diesem Issue das Problem von @Scream4Life behandelt wurde, bei welchem es um den "**handshake timeout**" ging, welches auf ein lokales Netzwerk-Problem zurückzuführen war, würde ich euch (@Luftloch80 @maikburd @chstoll) bitten ein neues Issue zu öffnen. 

Ich wünsche mir eine ausführliche **Debug-Log** (Homebridge mit -D starten), da ich das Problem bei mir noch nie reproduzieren konnte.

Gruß Nico
