### ISSUE TITLE
Room ID

### ISSUE THREAD

**Issue by roberkane212** [nicoh88/homebridge-xiaomi-roborock-vacuum#134]
Does anyone know how to find the ID’s of the rooms? I don’t see any of numbers in the app

**Comment by charliebird** [comment]
I have the same issue, a bit of documentation on this feature would be awesome

**Comment by normen** [comment]
The feature of the plugin is documented. What isn't documented is how the Roborock assigns the numbers and that isn't part of this plugin, it's part of the Roborock firmware.

Theres a simple solution: Make a bunch of rooms with id's from 1-32, set the names to 1-32 as well and start homebridge. Now in HomeKit start switch "1" and look in the Xiaomi app to which room the robot goes. Write that down, repeat for all numbers and then enter the number/room combinations you found in config.json.

**Comment by CameronVIE** [comment]
Thank you @normen. It worked for me - my rooms started with 16

**Comment by afharo** [comment]
This feature should solve the issue https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/#semi-automatic
Please, reopen it if it doesn't :)
