### ISSUE TITLE
Xiaomi Mi Robot Vaccum 1st Generation and rooms

### ISSUE THREAD

**Issue by WojtekWro** [nicoh88/homebridge-xiaomi-roborock-vacuum#136]
Hello
In first JSON example I see that the 1st generation xiaomi vacuum can work with rooms. Is that the truth?
How this works?

**Comment by afharo** [comment]
This feature should solve the issue https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/#semi-automatic
Please, reopen it if it doesn't :)
