### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by ArielZgo** [nicoh88/homebridge-xiaomi-roborock-vacuum#139]
While trying to load it via Homebridge plugins it responds with "permission denied". Full message below:

USER: pi
DIR: /usr/lib
CMD: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /home/pi/.npm/_cacache/tmp/git-clone-e931411e
npm ERR! /home/pi/.npm/_cacache/tmp/git-clone-e931411e/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-29T12_24_15_572Z-debug.log

Command failed. Please review log for details.

**Comment by CameronVIE** [comment]
seems you do not have git?
what tells 
which git
in cmd?

**Comment by ArielZgo** [comment]
Reinstalled everything and started to work. Closing the issue :)
