### ISSUE TITLE
Installation auf Raspberry Pi nicht möglich

### ISSUE THREAD

**Issue by send0r** [nicoh88/homebridge-xiaomi-roborock-vacuum#14]
Hallo, ich bekomme leider Probleme mit der Berechtigung beim Installieren auf einem Raspberry Pi.
Ohne sudo ist eine installation global generell nicht möglich. Falls ich aber nun mit sudo oder sudo su arbeite, bekomme ich folgende Ausgabe:

root@raspberrypi:/home/pi# npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /root/.npm/_cacache/tmp/git-clone-96e7cb85
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-96e7cb85' nicht erstellen.: Keine Berechtigung
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-14T14_05_42_510Z-debug.log

Gibt es noch andere Alternativen das Plugin zu installieren?

**Comment by nicoh88** [comment]
Hi @send0r,

ich vermute, du hast kein "git" installiert.

`sudo apt install git`

Danach den NPM-Befehl noch einmal ausführen.

Gruß Nico

**Comment by send0r** [comment]
Hi Nico, danke für die Antwort.

Ich habe git gerade heute installiert, nachdem die erste Fehlermeldung war, dass git nicht in $PATH gefunden werden konnte. Der Fehler ist dann verschwunden und durch eben den aktuellen ersetzt worden.

Daran kann es also leider nicht liegen.

Gruß send0r

**Comment by send0r** [comment]
Bei mir ist Raspbian lite (also ohne Desktop ) drauf. npm ist in der Version 6.0.1 falls das helfen sollte.

**Comment by nicoh88** [comment]
Hi @send0r,

ich konnte das Problem nicht nachstellen. 👎 

Kannst du mal die "/root/.npm/_logs/2018-05-14T14_05_42_510Z-debug.log" posten?
Welche NODEJS- und NPM-Version verwendest du?

Gruß Nico

**Comment by send0r** [comment]
Hi Niko,
erstmal danke, dass du dir solche Mühen machst...
Nodejs ist auf der Version 8.11.1
npm ist auf der Version 6.0.1

Hier die log-Datei. Vielleicht wirst du ja schlauer daraus als ich.

[2018-05-14T14_05_42_510Z-debug.log](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/files/2006265/2018-05-14T14_05_42_510Z-debug.log)

Danke nochmal.
Grüße
send0r

**Comment by nicoh88** [comment]
@send0r 

Mache dich mal mit zum `root`:
`sudo su -`

Lege dann das benötige Verzeichnis mal händisch an:
`mkdir -p /root/.npm/_cacache/tmp/git-clone-96e7cb85`

Führe dann nochmal folgenden Befehl aus:
`npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm`

Gruß Nico

**Comment by send0r** [comment]
Tip top, jetzt hat es geklappt 👍 
Interessant, dass sudo su alleine nicht gereicht hat, sondern auch der Bindestrich hinten dran musste.

Aber danke dir für den Aufwand!

**Comment by MVPat** [comment]
Hi Nico,

hab mir jetzt extra einen git account angelegt, weil ich genau das gleiche Problem habe und hier nicht weiterkomme.
nodejs v13.7.0
npm 6.13.6

ein dazugehöriges logfile: https://pastebin.com/SWTZdmfV

es hilft auch nichts, den Ordner per mkdir zu erstellen, da der Ordnername am Ende generiert wird.

Fällt dir da was ein?

**Comment by nicoh88** [comment]
@MVPat 

Bist du `root` wenn du `npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm` ausführst?

Du musst dich mit `sudo su -` das `-` ist wichtig!

**Comment by MVPat** [comment]
Hi Nico, danke dass du so schnell antwortest. 

Ja, ich hab mich mit `sudo su -` angemeldet.

**Comment by nicoh88** [comment]
Hmm, dann weiß ich auch nicht. Vorher mal das Verzeichnis `/root/.npm/_cacache` löschen?

`rm -Rf /root/.npm/_cacache`

**Comment by MVPat** [comment]
Hat leider auch nicht geholfen. Kann man den install-Befehl irgendwie aufsplitten?

**Comment by nicoh88** [comment]
Nicht das ich wüsste.

Eigentlich bei alle, lag es am am fehlenden MINUS bei `sudo su -`.

https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/53#issuecomment-504753616
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/26#issuecomment-433686459
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/23#issue-366435258
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/17#issuecomment-398042041

Kannst du mal einen Screenshot posten, wo man die Befehle sieht? DANKE

**Comment by MVPat** [comment]
Hab mal beide Versionen probiert.
ich bin nicht 100% fit in linux. Wenn ich nämlich `su root` eingebe, bekomme ich einen Fehler bei der Authentifizierung. Mit `sudo su -` kann ich mich als root einloggen. Hat das was zu bedeuten?
![image](https://user-images.githubusercontent.com/60730295/73921315-5fbaf080-48c7-11ea-9389-38f9e5f7407a.png)

**Comment by nicoh88** [comment]
WTF. 

`git --version`

**Comment by MVPat** [comment]
Hab es gelöst bekommen!
Für dich, bzw. alle die in Zukunft auch auf dieses Problem stoßen, das hat mir geholfen:
zuerst hab ich gecheckt, ob der npm cache einen Fehler hat: `npm cache verify`
dann hab ich mich als root eingeloggt wie vorher auch: `sudo su -`
dann hab ich den Installationsbefehl wie gewohnt eingegeben, nur mit einem Unterschied:
` npm install **--cache /tmp/empty-cache** -g homebridge-xiaomi-roborock-vacuum         --unsafe-perm`

Dieser Befehl wurde mir vorgeschlagen, als ich `sudo -s npm cache clean` eingegeben habe:

> On the other hand, if you're debugging an issue with the installer,         you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking         the actual one.

EDIT: git version 2.11.0
Denkst du es lag ursprünglich an der git version?

**Comment by nicoh88** [comment]
> EDIT: git version 2.11.0
> Denkst du es lag ursprünglich an der git version?

Ne, vermutlich nicht.

Danke für das Teilen der Lösung!!
