### ISSUE TITLE
Roomcleaning no avaible afer update 0.73

### ISSUE THREAD

**Issue by Donni1966** [nicoh88/homebridge-xiaomi-roborock-vacuum#142]
Hi, 
i do the update and this is my config (part)
        {
            "name": "RobiS5",
            "ip": "192.168.2.132",
            "token": "41497135637742575a54324669416266",
            "waterBox": false,
            "pause": true,
            "dock": true,
            "delay": false,
            "cleanword": "Saugen",
            "autoroom": true,
            "rooms": [
                {
                    "name": "Esszimmer",
                    "id": 1
                },
                {
                    "name": "Gästebad",
                    "id": 2
                },
                {
                    "name": "Küche",
                    "id": 3
                },
                {
                    "name": "Sportecke",
                    "id": 4
                },
                {
                    "name": "Office",
                    "id": 5
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        },

after restart homebridge (version 0.4.54-beta-10) the rooms not dislayed. 

I try autoroom true an false. nothing change.

**Comment by vek030** [comment]
Go back to 0.7.2 and it works.

**Comment by nicoh88** [comment]
@c-o-m-m-a-n-d-e-r @afharo

**Comment by c-o-m-m-a-n-d-e-r** [comment]
autoroom is only working for the s6. this option is only for autodetecting the rooms.
We need some kind of Log Files to debug.

But i don't having so much time at the moment ... please share a log where it isn't working then i will take a look

**Comment by Donni1966** [comment]
Hi, where find the log? 
Homebridge.err oder *.log? or anyway?

**Comment by Donni1966** [comment]
> autoroom is only working for the s6. this option is only for autodetecting the rooms.
> We need some kind of Log Files to debug.
> 
> But i don't having so much time at the moment ... please share a log where it isn't working then i will take a look

oh is is working for an s5 - work sind the last versions without any problems.  And no problem, is was only a information, my be useful - or not. I being back to 0.72 and all is fine. 

is there an option to activate a debug log for homebridge-xiaomi-roborock-vacuum? If yes, i can switch is on, give you a logfile and help.

**Comment by CameronVIE** [comment]
0.7.3 is working with S5 Max

**Comment by Donni1966** [comment]
> Have your rooms been 1 -5 befor too? My rooms start much higher

yes is was absolut the exact config. what do you mean? I never read any number from a config before i set it in previos versions. i let anaylse the room with den robot and than i try number one - let see where he ist driving an gib him the right name.

Thanx or the tip with the names. but i don´t use siri for cleaning. it is automatic oder manual start by time or if is it nessesorry.

**Comment by afharo** [comment]
This feature should solve the issue https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/#semi-automatic
Please, reopen it if it doesn't :)
