### ISSUE TITLE
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/new

### ISSUE THREAD

**Issue by nfstange** [nicoh88/homebridge-xiaomi-roborock-vacuum#143]
I am getting this error message and after the update the vacuum suction button does not look right 
![IMG_A4EC96B34C27-1](https://user-images.githubusercontent.com/52550843/78466649-410b8700-76c9-11ea-9a97-70e3cf1d5d9e.jpeg)

<img width="1806" alt="Screen Shot 2020-04-04 at 11 09 19 PM" src="https://user-images.githubusercontent.com/52550843/78466662-57b1de00-76c9-11ea-93ff-6963cf36c3fb.png">

**Comment by afharo** [comment]
@nfstange can you try removing your `node_modules` folder and reinstalling again your dependencies?

**Comment by afharo** [comment]
Is this still valid?
