### ISSUE TITLE
Roborock S6 Water Box

### ISSUE THREAD

**Issue by netRunner0** [nicoh88/homebridge-xiaomi-roborock-vacuum#144]
Can I find out when the opportunity to include wet cleaning in S6 will work?

**Comment by afharo** [comment]
Hi! Sure!

Can you help us to find out the right mapping for the values?

We are after some mapping like in this comment: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/79#issuecomment-576246934

In that other issue (for the S5Max) the value we attended was `water_box_mode` in the logs. Can you check what values are reported in yours when switching modes in the app?

**Comment by netRunner0** [comment]
See in the Homebridge log when I turn on wet cleaning in miHome?

**Comment by netRunner0** [comment]
`[4/12/2020, 17:47:05] [Roborock S6] MON changedCharging | roborock.vacuum.s6 | ChargingState is now false
[4/12/2020, 17:47:05] [Roborock S6] INF changedCharging | roborock.vacuum.s6 | Charging is cancelled
[4/12/2020, 17:47:05] [Roborock S6] INF changedCharging | roborock.vacuum.s6 | Robot not anymore in dock.
[4/12/2020, 17:47:05] [Roborock S6] INF changedCleaning | roborock.vacuum.s6 | Cleaning is ON.
[4/12/2020, 17:47:05] [Roborock S6] INF changedPause | roborock.vacuum.s6 | Paused not possible, no cleaning
[4/12/2020, 17:47:05] [Roborock S6] INF changedPause | roborock.vacuum.s6 | Paused possible
[4/12/2020, 17:47:05] [Roborock S6] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 105%
[4/12/2020, 17:47:05] [Roborock S6] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 105%, this speed is not supported
[4/12/2020, 17:47:05] [Roborock S6] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 105%, this speed is not supported
[4/12/2020, 17:47:21] [Hue] Кухня движение: set homekit motion from 0 to 1
[4/12/2020, 17:47:35] [Roborock S6] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 101%
[4/12/2020, 17:47:35] [Roborock S6] INF changedSpeed | roborock.vacuum.s6 | Speed was changed to 101% (Quiet), for HomeKit 38%`

105% - Wet cleaning

**Comment by netRunner0** [comment]
I changed the code, now wet cleaning by 15%
Then why do we need a separate switch - Waterbox?

**Comment by netRunner0** [comment]
watermodes.js

'use strict';

module.exports = {
  // S5-Max (https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/79#issuecomment-576246934)
  gen1: [ 
    // 0%      = Off
    { homekitTopLevel: 0, miLevel: 200, name: "Off" },
    // 1-35%   = "Light"
    { homekitTopLevel: 35, miLevel: 201, name: "Light" },
    // 36-70%  = "Medium"
    { homekitTopLevel: 70, miLevel: 202, name: "Medium" },
    // 71-100% = "High"
    { homekitTopLevel: 100, miLevel: 203, name: "Hight" }
  ],
gen3: [
    // 0%      = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
// 1-15%   = "Soft"
    { homekitTopLevel: 15, miLevel: 105, name: "Soft" },
    // 16-38%   = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 101, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 102, name: "Balanced" },
    // 61-77%  = "Turbo / Stark"
    { homekitTopLevel: 77, miLevel: 103, name: "Turbo" },
    // 78-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 104, name: "Max" }
  ]
};

**Comment by netRunner0** [comment]
models.js

'use strict';

const speedmodes = require('./speedmodes');
const watermodes = require('./watermodes');

module.exports = {
  'default': {speed: speedmodes.gen1},
  'rockrobo.vacuum.v1': [{speed: speedmodes.gen1}],
  'roborock.vacuum.c1': [{speed: speedmodes.gen1}],
  'roborock.vacuum.m1s': [{speed: speedmodes.gen3}],
  'roborock.vacuum.s5': [
    {speed: speedmodes.gen2},
    {firmware: '>=3.5.7', speed: speedmodes.gen3},
  ],
  'roborock.vacuum.s5e': [{speed: speedmodes.gen4, waterspeed: watermodes.gen1}],
  'roborock.vacuum.s6': [{speed: speedmodes.gen3, waterspeed: watermodes.gen3}],
  'roborock.vacuum.t6': [{speed: speedmodes.gen3}],
  'roborock.vacuum.t4': [{speed: speedmodes.gen3}],
  'roborock.vacuum.e2': [{speed: speedmodes.gen3}],
};

**Comment by netRunner0** [comment]
speedmodes.js

'use strict';

module.exports = {
  gen1: [
    // 0%       = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
    // 1-38%   = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 38, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 60, name: "Balanced" },
    // 61-77%  = "Turbo / Stark"
    { homekitTopLevel: 77, miLevel: 77, name: "Turbo" },
    // 78-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 90, name: "Max" }
  ],
  gen2: [
    // 0%      = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
    // 1-15%   = "Mop / Mopping / Nur wischen"
    { homekitTopLevel: 15, miLevel: 105, name: "Mop" },
    // 16-38%  = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 38, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 60, name: "Balanced" },
    // 61-75%  = "Turbo / Stark"
    { homekitTopLevel: 75, miLevel: 75, name: "Turbo" },
    // 76-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 100, name: "Max" }
  ],
  gen3: [
    // 0%      = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
// 1-15%   = "Soft"
    { homekitTopLevel: 15, miLevel: 105, name: "Soft" },
    // 16-38%   = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 101, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 102, name: "Balanced" },
    // 61-77%  = "Turbo / Stark"
    { homekitTopLevel: 77, miLevel: 103, name: "Turbo" },
    // 78-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 104, name: "Max" }
  ],
  // S5-Max (https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/79#issuecomment-576246934)
  gen4: [ 
    // 0%      = Off / Aus
    { homekitTopLevel: 0, miLevel: 0, name: "Off" },
    // 1-15%   = "Soft"
    { homekitTopLevel: 15, miLevel: 105, name: "Soft" },
    // 16-38%   = "Quiet / Leise"
    { homekitTopLevel: 38, miLevel: 101, name: "Quiet" },
    // 39-60%  = "Balanced / Standard"
    { homekitTopLevel: 60, miLevel: 102, name: "Balanced" },
    // 61-77%  = "Turbo / Stark"
    { homekitTopLevel: 77, miLevel: 103, name: "Turbo" },
    // 78-100% = "Full Speed / Max Speed / Max"
    { homekitTopLevel: 100, miLevel: 104, name: "Max" }
  ]
};

**Comment by afharo** [comment]
Sorry, from the title I understood the S6 model had a water box option where you can select the amount of water to use (apparently S5Max has that feature). 

If that's not the case, maybe the option of setting it to 15% (Mode 105) is enough for you?

**Comment by netRunner0** [comment]
I do not know how to do it
How?)

**Comment by netRunner0** [comment]
> Sorry, from the title I understood the S6 model had a water box option where you can select the amount of water to use (apparently S5Max has that feature).
> 
> If that's not the case, maybe the option of setting it to 15% (Mode 105) is enough for you?

There is an option, but you can not choose the amount of water
Therefore, an additional accessory (fan)

**Comment by netRunner0** [comment]
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/pull/160
