### ISSUE TITLE
Zone Cleaning

### ISSUE THREAD

**Issue by tman785** [nicoh88/homebridge-xiaomi-roborock-vacuum#148]
hey guys, I notice there is code in here for zone cleaning.  However, the readme does not specify exactly what parameters are expected as zone coordinates.  Can you shed some light here?

**Comment by tman785** [comment]
For anyone else looking for this ..... was able to get it working. Config json needs a zones section.  

"zones": [
                {
			"name":"Family Room",
			"zone":[[bot-x-coord,bot-y-coord,top-x-coord,top-y-coord,no-of-cleanings]]
		}
]
 
There's an issue with this line of code too, where we send the clean zone command
```
      if (state && !this.isCleaning) { // Start cleaning
        this.log.info(`ACT setCleaning | ${this.model} | Start cleaning Zone ${zone}, not charging.`);
        const refreshState = {
          refresh: [ 'state' ],
          refreshDelay: 1000
        };
        await this.device.call('app_zoned_clean', [zone], refreshState);
```

I borrowed some code from [SmileyDude's implementation of zones](https://github.com/Smileydude/homebridge-xiaomi-roborock-vacuum), and it seems to work, but not sure why:

```
        var zoneParams = [];
        for (var zon of zone) {
          if (zon.length == 4) {
              zoneParams.push(zon.concat(1));
          } else if (zon.length == 5) {
              zoneParams.push(zon);
          }
        }

        await this.device.call('app_zoned_clean',zoneParams,refreshState);

```

**Comment by afharo** [comment]
That's awesome! Thank you for finding out @tman785 

Would you mind creating a PR adding you fix and a bit of an explanation of the feature and how to use it in the README file? 🙏 

Thank you again!!

**Comment by tman785** [comment]
Sure!  I need to figure out why the snip of code I borrowed works.  I dont like the idea of using code that I have no idea what it's doing 🤷‍♂️ .  I'll debug it and figure it out.  My gut feeling is that I wont need the for loop

**Comment by afharo** [comment]
As far as I understand it, zones need to have a length of 5, where the last element is the number of repeats for that zone.

If it finds the zone has a length of 4, it assumes it's missing the repeat number and appends `1` it via the `.concat(1)` method.

**Comment by AlexG-78** [comment]
@tman785 I wanted to modify your suggestions as Iwould like to enable zone cleaning as well. 
Somehow my S5 only drives a few centimeters and goes back to dock. It seems that he cannot get the approriate coordinates.

Could you share your code snippet how you have enabled zone cleaning?
thanks

**Comment by afharo** [comment]
@tman785 it would be great if you could create a PR with your changes if you got them to work on your end. This way we can all benefit from it 😉

**Comment by tman785** [comment]
Got my pull request in.  To be honest, I've never done one (not a coder since college), so let me know if it's not correct.

**Comment by AlexG-78** [comment]
@tman785 Thanks for the PR. I still got a question about the actual coordinates:
I checked the API call on my S5.Request URL: http://192.168.10.95/api/start_cleaning_zone
The reuqest payload is [[29100, 29850, 31050, 31050, 1]] which is part of my kitchen. This call is invoked via Valetudo and works as expected.

When I use the extracted coordinates in the config.json my vaccum drives to a different position.
