### ISSUE TITLE
Stati werden nicht aktualisiert, wenn pause:true

### ISSUE THREAD

**Issue by chstoll** [nicoh88/homebridge-xiaomi-roborock-vacuum#15]
Hallo! 

Die Stati werden nicht korrekt aktualisiert. Aktuell zeigt der Sauger an, er würde mit 90% saugen und die Dockingstation hat nicht ausgelöst:

```
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Pause possible true.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Cleaning is true.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Fanspeed is 90%.
May 17 15:05:42 HomeKitPi homebridge[14310]: [2018-5-17 15:05:42] [Xiaomi Roborock S50] Docked is false.
```
Das ist aber nicht der Fall. Der Sauger steht auf der Dockingstation und ist nicht wirklich am saugen :-)
Starte ich homebridge neu, passt es wieder:

```
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Pause possible false.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Fanspeed is 90%.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Cleaning is false.
May 17 15:12:12 HomeKitPi homebridge[540]: [2018-5-17 15:12:12] [Xiaomi Roborock S50] Docked is true.
```
Meist wird schon nach dem ersten Saugvorgang das ganze nicht mehr richtig aktualisiert.

Debug-Log folgt in Kürze.

**Comment by chstoll** [comment]
Habe jetzt das Debug-Log aktiviert, seitdem konnte ich auch durch mehrere Start/Stop/Pause-Vorgänge das Problem bisher nicht reproduzieren (durchaus seltsam, bisher konnte ich das relativ schnell herbeiführen). Ich warte mal den morgigen kompletten Cleanup unserer Wohnung ab, mal schauen, ob dann noch alles passt.

**Comment by nicoh88** [comment]
Hi @chstoll,

ne so richtig bringt mich das nicht weiter. 😕 

💡: Kann es sein, dass die Probleme erst nach einer bestimmten Laufzeit von Homebridge auftreten? Ich starte beispielsweise meine Homebridge-Instanzen einmal am Tag, über die crontab neu.

✅: Bitte prüfen, ob es die ersten 12, 18, 24, ... Stunden ordentlich funktioniert und dann erst die Probleme auftreten. Wenn ja, müsste ein nach X ein Reconnect / Reinitialisieren einbauen.

Gruß Nico

**Comment by MattBN001** [comment]
Habe leider exakt das gleiche Problem.
Keine Möglichkeit dies zu lösen?

**Comment by nicoh88** [comment]
Hi @MattBN001,

natürlich kann man jedes Problem lösen. Aber vorab muss ich erstmal verstehen, warum ihr solche Probleme habt. Ich kann das Problem bei mir nicht reproduzieren / nachvollziehen.

Daher meine Fragen an euch! **Ihr müsste mir helfen bei der Eingrenzung des Problems.**

💡: Kann es sein, dass die Probleme erst nach einer bestimmten Laufzeit von Homebridge auftreten? Ich starte beispielsweise meine Homebridge-Instanzen einmal am Tag, über die crontab, neu - eventuell habe ich deswegen diese Probleme nicht.

✅: Bitte prüfen, ob es die ersten 12, 18, 24, ... Stunden ordentlich funktioniert und dann erst die Probleme auftreten. Wenn ja, müsste ein nach X ein Reconnect / Reinitialisieren einbauen.

Gruß Nico

**Comment by MattBN001** [comment]
Hallo Nico,

das war keinesfalls böse gemeint! ;)...


Also ich habe die mit der Laufzeit noch nicht verifizieren können, da ich meine Homebridge nicht automatisch neu starte. Kannst du einmal deinen Cron veröffentlichen, dann bau ich dies ggf mal ein...

Ich hatte meinen Homebridge gestern extra neu aufgesetzt, damit keine Probleme aus alten configs kommen. Habe den Robot 7-8 mal manuell gestartet und ins Dock fahren lassen, ohne Probleme. Habe in der Home-App eine Scene erstellt und diese per Automation heut morgen laufen lassen. Starten hat super geklappt, allerdings wurde am Ende wieder nicht erkannt, dass der Robi im Dock war. Im Log stand weiterhin, dass das Cleaning läuft.... Ich kann es leider nicht immer nachstellen.
Kann man ein zusätzliches Log aktivieren? 

Was mich ein wenig wundert: Ist es korrekt, dass dein Plugin die miio-Version 0.15.4 installiert? Ich hatte so ein wenig den Verdacht, das npm evtl. eine alte Version, ggf. ohne Fixe, installiert (wenn dies überhaupt technisch möglich ist).

**Comment by nicoh88** [comment]
@MattBN001 

Habe ich auch nicht so aufgefasst.
Eigenartig.

Crontab

```
# Homebridge neustart
30 5    * * *   root    service homebridge restart
```

Ja, mein Plugin installiert seine eigene Version von miio - diese liegt bei mir unter `/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/`. Richtig, es ist die 0.15.4, zusätzlich mit ein paar Fixes von mir, da der Entwickler leider nicht oft aktiv ist.

**Comment by nicoh88** [comment]
@MattBN001: Alles klar.

Welches "andere Xiaomi-Plugin" hast du installiert?

**Comment by nicoh88** [comment]
UPDATE: Meine Version ist auch die 0.15.6 - nur die packages.json wurde vergessen zu aktualisieren. Dies ist auch noch bei der offiziellen miio-Version der Fall.

**Comment by MattBN001** [comment]
Ich meinte diese Plugin:
https://www.npmjs.com/package/homebridge-xiaomi-mi-robot-vacuum
Allerdings gefällt mir deins deutlich besser, da es mehr Funktionen bietet.
Dient als Gegentest.
Und was auch nicht zu vernachlässigen ist: ein deutscher Entwickler muss unterstützt werden :)...
Der PayPal-Button ist bereits vorgemerkt und wird benutzt sobald ich eh eingeloggt bin!

Habe als Test vorhin nochmals die komplette Wohnung sagen lassen und dieses mal haben beide Plugins wie gewünscht funktioniert. Wie verhext...

Ich gebe weiterhin Feedback!

**Comment by MattBN001** [comment]
So, mal Feedback von mir:

bei mir funktionierte die Aktualisierung nun 3 Tage hintereinander ohne Probleme. Beide Plugins gaben jeweils den aktuellen und korrekten Status des Robis aus. 

Ich habe seit heute das "andere" Plugin deinstalliert und beobachte das Ganze noch ein wenig. Der Cron zum morgendlichen Neustart von Homebridge ist ebenfalls eingerichtet.

**Comment by Partyboy97** [comment]
@nicoh88 Ich glaube nicht das die Laufzeit der Homebridge das Problem ist. Vielmehr ist es der "Pause" Schalter. Der "Pause" Schalter wird nicht zurück gesetzt nach beenden des Saugvorgangs. Resultat ist, das bei erneuten Starten via Homekit der Vacuum nichts mehr macht, der Saugvorgang ist aktive, aber dirket in "Pause" Modus. Seitdem ich den "Pause" Schalter via Config.json ausgeschlossen habe, ist alles tuti.

**Comment by nicoh88** [comment]
@Partyboy97: Läuft weiterhin problemlos?

**Comment by MattBN001** [comment]
Also ich hatte den Pause-Schalter aktiviert, allerdings nie benutzt. Mittlerweile scheint es bei mir auch soweit zu laufen :)

Was ich getan habe:
- Node-JS auf Version 8 gedowngraded (von v10), wegen einem anderen Plugin
- Pauseschalter deaktiviert
- Frauchen verboten manuell etwas zu tun (über die Xiaomi App)
- Homebridge wird jeden Nacht neu gestartet 
- den Raspi mehrfach aktualisiert

Da ich den Raspi durch einen RockPro64 ersetzen möchte, werde ich alles einmal neu installieren müssen.
@nicoh88 welche Version von NodeJS setzt du denn ein? Ist die aktuellste Version offiziell supportet?

**Comment by MattBN001** [comment]
So, mal ein kleines Update von mir:

Homebridge läuft jetzt auf einem RockPro64, der deutlich leistungsfähiger ist.
Das Plugin läuft bei mir jetzt scheinbar problemlos, solange es keine äußeren Einflüsse gibt.

- Was gestern passiert ist: Staubsauger läuft, HomeKit zeigt beim Dock "keine Anwesenheit" und die Drehgeschwindigkeit --> alles korrekt.
- Staubsauger bleibt stehen, da die Bürste blockiert ist, im HomeKit zeigt beim Dock "keine Anwesenheit", Drehgeschwindigkeit auf "0" --> alles korrekt.
- Staubsauger wird später befreit und per Knopf auf dem Roboter wieder gestartet. HomeKit aktualisiert die Werte nicht. --> nicht korrekt
- Staubsauger ist fertig und kehrt ins Dock zurück, HomeKit bleibt weiterhin bei "keine Anwesenheit" und Drehzahl "0" --> nicht korrekt
- Neustart von Homebridge und alles passte wieder....

**Comment by chstoll** [comment]
Ich habe jetzt auch mal den Pause-Schalter deaktiviert. Seitdem gibts keine Probleme mehr, auch ohne Neustart der Homebridge.

**Comment by nicoh88** [comment]
Hallo @chstoll @MattBN001,
mit der neuen Version 0.4.0 sollte das Problem mit der "Pause" Funktionalität behoben sein.

`npm install -g --unsafe-perm homebridge-xiaomi-roborock-vacuum@latest`

Danke an @Partyboy97, dass du das genaue Probleme lokalisieren konntest.

**Comment by paskovitch** [comment]
In der neuen Version ist es auch nich funkzioniert. :(

**Comment by nicoh88** [comment]
@paskovitch 

Bitte ein neues Issue mit einer ausführlichen **Debug-Log** öffnen. Dann sind natürlich auch die **Timestamps** wichtig, wann das Problem auftritt, wann der Status nicht aktualisiert wurde, und so weiter. Bitte auch nicht nur einen Beispielfall sondern mehrere. DANKE

Sonst kann ich das Problem leider nicht beheben, da bei mir keine solchen Probleme auftreten. Sorry.

In der Regel dauert es bis zu 30 Sekunden, bis er eine Status-Änderung über inoffiziell miIO-API mitbekommt.

Um Homebridge im Debuging-Mode für das `homebridge-vorwerk` Plugin zu starten, muss während oder vor dem Start `DEBUG=homebridge-vorwerk` gesetzt werden. Je nachdem Unterschiedlich, wie du Homebridge verwendest bzw. startest.

Beispiel:
`sudo DEBUG=homebridge-vorwerk homebridge -D -U /var/lib/homebridge`

Viele Grüße
Nico
