### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by DoctorGremlin** [nicoh88/homebridge-xiaomi-roborock-vacuum#151]
Hi,
i am getting an error while installing the plugin as root:

root@raspberrypi:~# npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm

> deasync@0.1.19 install /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync
> node ./build.js

make: Verzeichnis „/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync/build“ wird betreten
  CXX(target) Release/obj.target/deasync/src/deasync.o
make: g++: Kommando nicht gefunden
deasync.target.mk:107: die Regel für Ziel „Release/obj.target/deasync/src/deasync.o“ scheiterte
make: *** [Release/obj.target/deasync/src/deasync.o] Fehler 127
make: Verzeichnis „/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/deasync
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.19 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-15T16_46_17_998Z-debug.log

Any idea how to solve this?

Greetz,
Doc

**Comment by afharo** [comment]
It looks like you cannot compile because `g++` is not installed.

I see you have a Raspberry PI so I'm assuming you are running Raspbian.

Can you try running the command `sudo apt-get install build-essential` and then repeat the install command?

**Comment by DoctorGremlin** [comment]
That was my first thought, but i get a message that build-essential is already the newest version (12.3).

**Comment by afharo** [comment]
Oh! Weird! I’ve been Googling around and some folks say `sudo apt-get install gcc` or `sudo apt-get install g++` worked for them

**Comment by afharo** [comment]
Also try ensuring you have the latest updated list before running those commands by running `sudo apt-get update`

**Comment by DoctorGremlin** [comment]
Just made the update and upgrade, nodejs was updated from v12.16.1 to 12.16.2, and node-gyp from 5.0.5 to 5.1.0.
The installation of g++ and gcc told me it was already the latest version.
The installation of the homebrigde-plugin still fails with the same error (except the newer version numbers).

**Comment by afharo** [comment]
@DoctorGremlin can you try installing from the branch in the PR https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/pull/158 ?

I moved the dependency that is failing to build to optional, so even when it fails, the installation should go on. We only use that library for the `delay` feature, so we should be fine like that.
