### ISSUE TITLE
Change Logs in Config-UI-X

### ISSUE THREAD

**Issue by mitch7391** [nicoh88/homebridge-xiaomi-roborock-vacuum#153]
Hi, I was wondering if you can make your change logs appear in config-ui-x? Some plugins when updated on that UI have a pop-up box that lists the latest updates to the plug-in :)

**Comment by afharo** [comment]
Hi! Are there any recommendations/documentation to know the necessary changes to achieve that?

**Comment by afharo** [comment]
In the latest version, I tried using the tags and releases feature in Github. Plus we moved the Changelog from `README.md` to the `CHANGELOG.md` file. Not sure if it helped.

**Comment by mitch7391** [comment]
I will install the update after work and update on you :)

**Comment by mitch7391** [comment]
That has worked :) although it is showing your entire change log, not your most recent entry; but it is better than nothing!

**Comment by afharo** [comment]
Cool! Let’s see if the next release will only show the diff 🤞  

Can I close this issue then?

**Comment by mitch7391** [comment]
Awesome :) thanks for the speedy work!
