### ISSUE TITLE
Auto room detection shows "numbers" as the room name

### ISSUE THREAD

**Issue by petschni** [nicoh88/homebridge-xiaomi-roborock-vacuum#154]
The auto room detection feature is kind of working for me. When booting up homematic it will detect the rooms configured with the `Xiamoi Home` app. But instead of the names it will show me an ID:

``` 
INF createRoom | roborock.vacuum.s6 | Room 579221910468 (16)
```

Anything I can do about that or is that the expected result?

**Comment by afharo** [comment]
#152 is in the works that may fix this issue :)

**Comment by petschni** [comment]
> #152 is in the works that may fix this issue :)

I tried that branch but it did not solve the issue for me. Maybe the cause is that I used the `roborock` app first and only later switched to the `Xiamoi Home` app and named the rooms?
