### ISSUE TITLE
Resume im Zoned Cleanup-Mode startet komplettes Cleanup

### ISSUE THREAD

**Issue by chstoll** [nicoh88/homebridge-xiaomi-roborock-vacuum#16]
Hallo,

beim Testen ist mir Folgendes aufgefallen:

-Zoned Cleanup über MiHome gestartet
-Pause über HomeKit ausgelöst
-Resume über HomeKit löst dann einen kompletten Cleanup aus (müsste eigentlich ein "Resume Zoned Cleanup" auslösen

**Comment by nicoh88** [comment]
@chstoll Beim SpotCleaning auch oder?

**Comment by nicoh88** [comment]
Leider nicht möglich, da es über die miio-API kein "Pause Ende" oder "Zurück zum letzten Zustand gibt" - sondern nur "Starten", "Starte Spot" und "Starte Zone". Homebridge kennt leider den Zustand nicht, der über die MiHome-App gesetzt wurde.

**Comment by suxus-zz** [comment]
Hallo, ist es möglich mit dem Plugin die Zonenreinigung zu definieren, so dass man über die Home-App (iOS) dann entweder das ganze Haus reinigen will oder nur eine entsprechende Zone (z.B. Eingangsbereich)? Vielen Dank

**Comment by nicoh88** [comment]
Hallo @suxus-zz,

das Zone-Cleanup ist komplex als du denkst.
Du könntest aber zu meinem Plugin auch noch, dass [homebridge-xiaomi-roborock-vacuum-zones](https://www.npmjs.com/package/homebridge-xiaomi-roborock-vacuum-zones) nutzen und dir ein, zwei, drei Kacheln für deine Bereiche erstellen.

Viel Glück!

**Comment by suxus-zz** [comment]
Ja dass kann ich mir schon vorstellen. Ich habe das Zones-Plugin auch gesehen, doch wenn ich dass dann korrekt verstanden habe, würde dieses Plugin an Dein Plugin ersetzen, beide zusammen geht dann wohl nicht, sprich Dein Plugin für die ganze Haus Reinigung und das andere Plugin für gezielte Zone-Reinigung.
Vielen Dank

**Comment by nicoh88** [comment]
Hi @suxus-zz,

möglich, dass beide Plugins nicht gleichzeitig verwendbar sind. Das könnte aber der Entwickler des Zones-Plugin @Smileydude ändern - liegt, denke ich, nur am Pluginnamen (accessory Zeile) in der `config.json`.

**Comment by suxus-zz** [comment]
Ich denke Du meinst diesen Eintrag

"accessory": "XiaomiRoborockVacuum"

der müsste aber @Smileydude ändern, ich kann da nichts machen oder? Er müssen bei sich wohl sowas machen.

"accessory": "XiaomiRoborockVacuumZones"

und dann könnten beide Plugins miteinander laufen. Weiss Du wo man diesen Entwickler erreichen kann?

Vielen Dank

**Comment by nicoh88** [comment]
Genau. Bin zwar kein Experte, aber ich denke, dass das der Grund ist.

Mache einfach ein Issue bei ihm im GitHub auf.
