### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not complete call to device 

### ISSUE THREAD

**Issue by Partyboy97** [nicoh88/homebridge-xiaomi-roborock-vacuum#17]
Hi all,
i've got a problem with my vacuum. Firmware is 3.3.9_003170 / Miio 15.6. Only every 2 command will execute by the vacuum.

Jun 14 17:57:35 homebridgepi homebridge[1835]: (node:1835) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
Jun 14 17:57:35 homebridgepi homebridge[1835]: at checkResult (/usr/local/lib/node_modules/miio/lib/devices/vacuum.js:13:9)
Jun 14 17:57:35 homebridgepi homebridge[1835]: at
Jun 14 17:57:35 homebridgepi homebridge[1835]: (node:1835) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jun 14 17:57:35 homebridgepi homebridge[1835]: (node:1835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nicoh88** [comment]
Hi,

i think you have not installed the latest version. Which version of my plugin do you have installed?

npm -g list --depth=0 | grep -i homebridge-xiaomi-roborock-vacuum

**Comment by Partyboy97** [comment]
Hi Nico,

i've replaced the index.js and package.json with the code from github. The Error appears in the log, but it the robot execute all command and the Dock sensor work properly.

**Comment by nicoh88** [comment]
Ah, da ist der Fehler. Mein Plugin hat ein eigenes Miio, welches er bei der NPM Installation mit installiert.

Mit welchem Befehl machst du dich zum `root`?
Du musst `sudo su -` verwenden, mit dem Minus.
Danach nochmal den normalen NPM Installationsbefehl.

Gruß Nico

**Comment by Partyboy97** [comment]
Hm `sudo -i`

Jetzt hat die installation via NPM geklappt und alles sieht fein aus. Danke dir.
