### ISSUE TITLE
Pause button is the wrong way round

### ISSUE THREAD

**Issue by bertybassett** [nicoh88/homebridge-xiaomi-roborock-vacuum#18]
At present
when I start the vacuum, the pause button is highlighted and says on

when I press the pause button it dims/greys out and says off

I think it should work like this
when I start the vacuum the pause button dims/greys out and say off

when I press the pause button it dims/greys out and say on

Or is this by design for some reason that I can not figure out?

**Comment by nicoh88** [comment]
It's complicated, if you reverse the logic, the pause button will show an exclamation point. You have to see the button "pause" as "pause possible".
