### ISSUE TITLE
Verschleißanzeige 

### ISSUE THREAD

**Issue by Nastras** [nicoh88/homebridge-xiaomi-roborock-vacuum#2]
Die Werte die du ausgegeben bekommst sind das die Prozente wie in der Mi App oder wie in deinem Beispiel 12345 Std noch übrig bis zum Wechsel?

**Comment by nicoh88** [comment]
@Nastras 

Ich bekomme die Laufzeit in Sekunden.

```
[ { main_brush_work_time: 163962,
    side_brush_work_time: 163962,
    filter_work_time: 163962,
    sensor_dirty_time: 163958 } ]
```

Sensor: 163958/60/60 = **45 Stunden**

Nach einem "_Cleaned_", über die App, dann ...

```
[ { main_brush_work_time: 163962,
    side_brush_work_time: 163962,
    filter_work_time: 163962,
    sensor_dirty_time: 0 } ]
```

... angezeigt.

**Comment by SeydX** [comment]
@nicoh88

Nastra hat mich gebeten hier mal vorbeizuschauen wegen der Verschleiß Anzeige in HomeKit

Da ich leider kein Xiaomi Roboter besitze kann ich nur oberflächlich was zu sagen

Man könnte ja eine eigene Characteristic erstellen und dieser dann die Werte der Verschleißanzeige zuteilen so dass zb in der EVE app man die Möglichkeit hätte diese zu sehen

**Comment by nicoh88** [comment]
@SeydX @Nastras 

Ich schaue es mir bei Gelegenheit genauer an. 😄 
Danke für euerer Feedback. 👍 

Läuft ansonsten alles?

---------------

**Zur Info** 
Der Watchdog (wenn der Stausauger über die MiHome App gestartet wird, bekommt es Homebridge nur so mit) steht aktuell auf 30 Sekunden. Bei meinen Tests (intern) hatte ich es auf 10 Sekunden, da hat sich nach ca. 18 Stunden der Saugroboter auf Werkseinstellungen zurückgesetzt. :flushed: Total strange - also neu ins WLAN verbinden, Token auslesen, usw. 

Entweder haben die ein Daily-Limit die der Token "missbraucht" werden kann oder es gibt einen Fehler im [miio](https://github.com/aholstenson/miio) Paket.

Jemand von euch was mitbekommen?

**Comment by Nastras** [comment]
Hey @nicoh88 bezüglich deines Fehlers denn du oben beschreibst habe ich noch nichts gesehen, zum Glück .-). 
Scheint also was gebracht zu haben die Zeit auf 30 Sek zu stellen.

Hier aber ein anderer Fehler, Ich bekomme aber nach jedem Reboot, diese Meldung einmalig angezeigt im Homebridge Journal deines Plugin:

Mär 25 04:14:47 HomeBridgeServer homebridge[618]: (node:618) UnhandledPromiseRejectionWarning: undefined
Mär 25 04:14:47 HomeBridgeServer homebridge[618]: (node:618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Was die Erweiterung angeht mit der Verschleißanzeige, @SeydX hatte mir gestern gesagt das er dir gerne dabei helfen kann bzw. dir auch etwas genauer erklären würde wie es geht falls da Bedarf besteht.

Bin leider selber auch nicht der Große Plugin Programmierer -.-


Ps: Habe dein Skript für die FB gestern entdeckt, feine Sache !

**Comment by Nastras** [comment]
Noch kurz angemerkt ich nutze node 9.9.0 da es ja ein node Fehler ist.

**Comment by nicoh88** [comment]
"Unhandled promise rejections are deprecated" wird bereits in #3 abgearbeitet.

[Warte auf "merge"](https://github.com/aholstenson/miio/issues/137) von @aholstenson, dann kann es hier weitergehen 😉

**Comment by nicoh88** [comment]
**@Nastras** 

Hast du es dir so vorgestellt?

![img_9163](https://user-images.githubusercontent.com/264264/38926086-c10c09f0-4301-11e8-807c-a5b6029a87d5.png)

Ich habe mich dazu entschlossen, die Werte in % anzeigen zu lassen, da ja alle vier eine andere Lebenszeit haben.

- 30h = Sensoren
- 150h = Filter
- 200h = Seitenbürste
- 300h = Hauptbürste

Die 292% bei Sensoren heißt in meinem Fall, dass ich die Sensoren seit fast 90 Stunden nicht gereinigt bzw. den Zähler über die [Mi Home App](https://itunes.apple.com/de/app/mi-home-xiaomi-smarthome/id957323480?mt=8) nicht zurückgesetzt habe.

**Comment by Nastras** [comment]
Hey, ho @nicoh88 

> Hast du es dir so vorgestellt?
Genau so 👍

> Ich habe mich dazu entschlossen, die Werte in % anzeigen zu lassen, da ja alle vier eine andere Lebenszeit haben.

Ich denke das ist voll in Ordnung.

> Verbesserungen? Vorschläge?
Der Text kann geändert werden in denn Einstellungen um es manuell auf Deutsch anzupassen?

> Ich habe bisher noch nicht herausgefunden, wann sich die Werte aktualisieren... während der Reinigung jedenfalls nicht. 👎
Das bekommen wir schon raus 😉


Ansonsten sieht es sehr gut aus 👍👍👍 Danke dir👌

Wann kann man mit dem Update rechnen?

**Comment by nicoh88** [comment]
@Nastras: Version 0.3.0 wurde veröffentlicht. 😉
