### ISSUE TITLE
No git binary found in $PATH

### ISSUE THREAD

**Issue by patrik72** [nicoh88/homebridge-xiaomi-roborock-vacuum#20]
root@raspberrypi:~# npm -g i --unsafe-perm homebridge-xiaomi-roborock-vacuum
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t git://github.com/nicoh88/miio.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by nicoh88** [comment]
apt install git
