### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by koalalorenzo** [nicoh88/homebridge-xiaomi-roborock-vacuum#21]
Hello!
Have you thought about translating the readme to English?

**Comment by nicoh88** [comment]
No. Sorry.

**Comment by eivindml** [comment]
Would love english version as well. Why not do it? I'm sure me and others could help with it, and you would have a bigger audience.

**Comment by nicoh88** [comment]
@eivindml @koalalorenzo

Fork it, translate the readme, create a pull request, i merge it. :1+

**Comment by koalalorenzo** [comment]
I decided to not do that honestly. Not sure why I should help somebody that is rude by not explaining why.

**Comment by nicoh88** [comment]
@eivindml @koalalorenzo

Done. Can you check typo with a pull request?
Thanks
