### ISSUE TITLE
Roborock S50 / „keine Antwort“ @ HomeKit

### ISSUE THREAD

**Issue by JuPePaLe** [nicoh88/homebridge-xiaomi-roborock-vacuum#22]
Hallo Zusammen,

in HomeKit bekomme ich für den S50 „keine Antwort“. Ich habe sowohl die Gen1 im Einsatz. Hierfür funktioniert es einwandfrei (Danke dafür!).

Was mich etwas irritiert ist, dass ich bei Nutzung von „miio discover“ zwei mal die Rückmeldung bekomme:

Model Info: rockrobo.vacuum.v1

Natürlich andere device ID und IP. Beide Staubsauger sind im Netzwerk und können auch über die MI Home App gestartet werden.

Wäre für jede Hilfe dankbar.

Gruß
Peter

**Comment by nicoh88** [comment]
Ich denke, das der Token des S50 falsch ist. Kannst du das bitte nochmal prüfen?

Danke

**Comment by nicoh88** [comment]
No reply since more then 2 months. CLOSE 📕
