### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by josba91** [nicoh88/homebridge-xiaomi-roborock-vacuum#23]
Hi!
Ich bekomme beim Installieren einen Permission denied Error. Wie kann ich das beheben?

Mein Log:

pi@raspberrypi:~ $ sudo npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /root/.npm/_cacache/tmp/git-clone-c87a3272
npm ERR! /root/.npm/_cacache/tmp/git-clone-c87a3272/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-03T16_52_50_472Z-debug.log
pi@raspberrypi:~ $ nano /root/.npm/_logs/2018-10-03T16_52_50_472Z-debug.log

  GNU nano 2.7.4                                         File: /root/.npm/_logs/2018-10-03T16_52_50_472Z-debug.log                                                   

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-xiaomi-roborock-vacuum',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@5.6.0
3 info using node@v9.9.0
4 verbose npm-session 0e43bd550682c482
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-xiaomi-roborock-vacuum 681ms (from cache)
8 silly pacote tag manifest for homebridge-xiaomi-roborock-vacuum@latest fetched in 802ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-xiaomi-roborock-vacuum@0.3.2 checking installable status
14 silly fetchPackageMetaData error for miio@git://github.com/nicoh88/miio.git#master Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nic$
14 silly fetchPackageMetaData /root/.npm/_cacache/tmp/git-clone-c87a3272/.git: Permission denied
15 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /root/.npm/_cacache/tmp/git-clone-c87a3272
15 verbose stack /root/.npm/_cacache/tmp/git-clone-c87a3272/.git: Permission denied
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:273:12)
15 verbose stack     at ChildProcess.emit (events.js:180:13)
15 verbose stack     at maybeClose (internal/child_process.js:936:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:353:11)
15 verbose stack     at Socket.emit (events.js:180:13)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:541:12)
16 verbose cwd /home/pi
17 verbose Linux 4.14.50-v7+

**Comment by ThomasBoettner** [comment]
Hallo, teste mal unter root.
Su root

**Comment by josba91** [comment]
Super, hat funktioniert. Danke!
