### ISSUE TITLE
Possible to add a button for S50 to return to dock station?

### ISSUE THREAD

**Issue by maisun** [nicoh88/homebridge-xiaomi-roborock-vacuum#28]
Hi, thanks for the great plugin, it works for me flawlessly.
Would it be possible to make the robot going back to charging dock when paused?
Thanks!

**Comment by nicoh88** [comment]
Hi @maisun,

thanks. Yes, it was be possible. 

But is it not the really function of "pause".
Pause is pause, not "back to charging dock".

Sorry.
