### ISSUE TITLE
Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by davidh2k** [nicoh88/homebridge-xiaomi-roborock-vacuum#29]
I get this after setting up your plugin:

`[Xiaomi Roborock] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

I did verifiy that I got the correct token:

mirobo --ip 192.168.178.72 --token $MyToken
State: Charging
Battery: 100 %
Fanspeed: 100 %
Cleaning since: 0:34:54
Cleaned area: 33.4125 m²

I'm happy to supply more information, but as far as I can tell, the debug log doesn't even show the error message shown above, let alone the any more info. Running homebridge via https://github.com/oznu/docker-homebridge

{
    "bridge": {
        "name": "Homebridge",
        "username": "$Username",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "XiaomiRoborockVacuum",
            "name": "Xiaomi Roborock",
            "ip": "192.168.1.72",
            "token": "$MyToken",
            "pause": false,
            "dock": true
        }
    ],
    "platforms": [
        {
            "platform": "MaxCubePlatform",
            "name": "MaxCube Platform",
            "ip": "192.168.178.71",
            "port": 62910
        }
    ]
}

Greetings
David

**Comment by nicoh88** [comment]
Hi @davidh2k,

that sounds very strange.

Can you rule out a **typing error**?
Are **special characters** in the token?

For me and some other users, the plugin runs without problems.

Kind regards, Nico

----

**UPDATE:** Uhhhhh change "192.168.1.72" in your config to "192.168.178.72". 😅

**Comment by davidh2k** [comment]
Uuuuh... oh boy... thank you for pointing that error out... No idea how i could miss THAT. You can close the issue. ;)
