### ISSUE TITLE
Feature request: show the status of Roborock in HomeKit when start cleaning from Mi Home 

### ISSUE THREAD

**Issue by maisun** [nicoh88/homebridge-xiaomi-roborock-vacuum#30]
Hi,
The plugin works well when I start clean in HomeKit, and I can also see the little thing moving in Mi Home. 
If I start it in Mi Home (normally for zoned cleaning) however, HomeKit still thinks the device is sleeping at the charging dock.
Can't the plugin read the status of the device and show in HomeKit?

**Comment by nicoh88** [comment]
It should work.

After circa 30 seconds, the new status should be displayed in the HomeKit.

**Comment by maisun** [comment]
Hi Nico, thank you for your reply!
It doesn’t seem to work for me no matter if I choose to do zoned cleaning or full cleaning from Mi Home. HomeKit thinks the robot still in the dock. I checked the HomeBridge log and found no errors, and there is no trace that shows the plugin pulls the status from the robot periodally. Anything else I should check?

**Comment by nicoh88** [comment]
Hi @maisun,

a try, I think it's a bug in the pause feature.

Do you have in the config.json `"pause": true`? 
If so, put `"pause": false`, restart homebridge and test it again.

I have not had time to solve the problem #15.

Please let me know if it works. ❓

**Comment by maisun** [comment]
Hi Nico,
I disable "pause" and started a full house clean job in Mi Home, and I could see HomeKit status was changed from off to 60%  which is good. However after the clean job finished and the device went back to the charging dock, HomeKit still thinks it's running 60% and shows wrong battery status 34% even though it was fully charged. I tried to turn off the fan in HomeKit but after a few seconds it switched back on again. So disabling pause didn't solve the problem completely.

**Comment by JonoHaysom** [comment]
I have the same issue as @maisun :(

@nicoh88 is there anything we can do to help troubleshoot or debug?

**Comment by th3cube** [comment]
Im switching back to https://www.npmjs.com/package/homebridge-xiaomi-mi-robot-vacuum

Its working flawlessly for me

**Comment by nicoh88** [comment]
@JonoHaysom

Do you have in the config.json "pause": true?
If so, put "pause": false, restart homebridge and test it again.

**Comment by nicoh88** [comment]
Hello @maisun @JonoHaysom @th3cube,

i have just released version 0.4.0. Please update the following command:

`npm install -g --unsafe-perm homebridge-xiaomi-roborock-vacuum@latest`

**The bugs should be fixed.**

If you continue to experience problems, please open a new issue with a homebridge debug log file (drag'n'drop) and the timestamps when the robot was started, when it finished/stopped, and when the status should have been updated.
In general, it may take up to 30 seconds for my plugin to receive the status change via the unofficial miIO API.

Thank you

**Comment by JonoHaysom** [comment]
it was fixed for me 👍 

I removed the old pause function and that fixed it. I might re add pause now if that issue was fixed! 

thanks for the hard work.

ill be adding a SmartMi Humidifier 2 to my XiaoMi homebridge lineup :D
