### ISSUE TITLE
Mopping 

### ISSUE THREAD

**Issue by charliebird** [nicoh88/homebridge-xiaomi-roborock-vacuum#31]
Hi,
Thanks for the plugin, works really well!
I've got the new gen Roborock, which does mopping as well as vacuuming. Is it possible to build a mop function to the plugin?
Thanks,

**Comment by Aekung** [comment]
Sorry for the recklessness. I have just found that there really is an option for mopping mode in the setting. Almost a year of using this machine, I have just found this hidden mode thanks to you. loll

**Comment by charliebird** [comment]
Yeah it's a special mode that runs with suction off I think. The plugin wouldn't work with that as to run it needs to be set to a suction level (1-100%). 
Glad you discovered this new function 😉

**Comment by leonardpitzu** [comment]
Suction is not off - its just a special mode which has the suction on and the advance (pace at which is moving through the room) is slower. Look for this in https://github.com/Hypfer/Valetudo - it' been discussed over there.

**Comment by nicoh88** [comment]
Please update to new version 0.4.0.

`npm install -g --unsafe-perm homebridge-xiaomi-roborock-vacuum@latest`

From 1% until 15% fanspeed is now mopping.
