### ISSUE TITLE
[suggestion] Valetudo compatibility

### ISSUE THREAD

**Issue by leonardpitzu** [nicoh88/homebridge-xiaomi-roborock-vacuum#32]
#1 congrats for the plugin
#2 the vacuum was "rooted" and shell (e.g. ssh) is now available. Dustcloud and Dummycloud offer solutions to use the vacuum without xiaomi cloud. Valetudo (https://github.com/Hypfer/Valetudo) offers a (best!) solution to use the vacuum fully without any of xiaomi's stuff. It would therefore be great to have your plugin support valetudo using its own exported API.

**Comment by aebgit** [comment]
+1 here. 
Valetudo makes it so easy to get rid of xiaomi-cloud and the api-key hassle. Would be great to have a homebridge-plugin that talks directly to valetudos-api.

**Comment by nicoh88** [comment]
Hi @leonardpitzu, hi @aebgit,

thanks for the info about Valetudo, so far I have not heard of it.

But, sorry. I will not customize my plugin for the Valetudo API. This plugin is just for the unofficial Xiaomi API. But, you may like to make a copy of my plugin, make the edits yourself and publish it as a new plugin on NPM. I'm sure this plugin want to use others! 👍 

Many Greetings
Nico

**Comment by onfoot** [comment]
I may help you with that with [my plugin](https://www.npmjs.com/package/homebridge-valetudo-xiaomi-vacuum) I published just yesterday. ;)

**Comment by aebgit** [comment]
@onfoot Awesome!! Works like a charm and out of the box!!!
