### ISSUE TITLE
Automated vacuum cleaning does not work

### ISSUE THREAD

**Issue by paskovitch** [nicoh88/homebridge-xiaomi-roborock-vacuum#33]
When I want to start vacuuming at a certain time, the icon becomes active and the pause icon, but the vacuum cleaner does not start. If I start manually, it works. I set the speed to 100%. I do this automation with this program: [https://itunes.apple.com/us/app/controller-for-homekit/id1198176727?mt=8](https://itunes.apple.com/us/app/controller-for-homekit/id1198176727?mt=8) I have a V1 type vacuum cleaner. Do I spoil something?

**Comment by nicoh88** [comment]
Hallo @paskovitch,

ich starte so jeden Tage meinen V1 und V2 ohne Probleme.
Nur habe ich für meine Automation die originale Apple Home App verwendet.

Bitte erstmal über Apple Home und Automationen testen.

Danke.

**Comment by paskovitch** [comment]
Hello @nicoh88 .

Thanks, I'm doing a try.

**Comment by nicoh88** [comment]
Will you let me know if it worked?

**Comment by paskovitch** [comment]
Yes, it worked! Thank you!
