### ISSUE TITLE
Clean Zones implementation

### ISSUE THREAD

**Issue by xaviplazas** [nicoh88/homebridge-xiaomi-roborock-vacuum#35]
Hi Nicoh88, Congratulations for the plugin, you plan to implement cleaning zones in the same way as the plugin "homebridge-xiaomi-roborock-vacuum-zones 0.3.7"?

Thanks for all!!

**Comment by nicoh88** [comment]
Nope, that's a very complex matter. But you are welcome to use his plugin.
