### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum

### ISSUE THREAD

**Issue by ttambourine** [nicoh88/homebridge-xiaomi-roborock-vacuum#37]
Hey guys, 
The accessory does not load when I restart home bridge since editing my config file.

Jan 25 19:39:34 raspberrypi homebridge[31946]: [2019-1-25 19:39:34] ====================
Jan 25 19:39:34 raspberrypi homebridge[31946]: [2019-1-25 19:39:34] ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
Jan 25 19:39:34 raspberrypi homebridge[31946]: [2019-1-25 19:39:34] TypeError: Path must be a string. Received undefined
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at assertPath (path.js:28:11)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Object.join (path.js:1233:7)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at userData (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node
_modules/appdirectory/lib/appdirectory.js:21:29)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at AppDirectory._setTemplates (/usr/lib/node_modules/homebridge-xiaomi-ro
borock-vacuum/node_modules/appdirectory/lib/appdirectory.js:134:34)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at new AppDirectory (/usr/lib/node_modules/homebridge-xiaomi-roborock-vac
uum/node_modules/appdirectory/lib/appdirectory.js:129:10)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-v
acuum/node_modules/miio/lib/tokens.js:8:14)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Module._compile (module.js:653:30)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Object.Module._extensions..js (module.js:664:10)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Module.load (module.js:566:32)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at tryModuleLoad (module.js:506:12)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Function.Module._load (module.js:498:3)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Module.require (module.js:597:17)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at require (internal/module.js:11:18)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/network.js:9:16)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Module._compile (module.js:653:30)
Jan 25 19:39:34 raspberrypi homebridge[31946]:     at Object.Module._extensions..js (module.js:664:10)
Jan 25 19:39:34 raspberrypi homebridge[31946]: [2019-1-25 19:39:34] ====================
Jan 25 19:39:34 raspberrypi homebridge[31946]: [2019-1-25 19:39:34] Loading 3 platforms...

"accessories": [
        {
  "accessory": "XiaomiRoborockVacuum",
  "name": "Dirty Debbie",
  "ip": "192.168.0.2",
  "token": "token_No",
  "pause": false,
  "dock": true
 }
]

Why is it not loading? I've reinstalled the app a couple of times now with no change.

Please help!

**Comment by nicoh88** [comment]
https://www.loggn.de/homebridge-xiaomi-mi-robot-vacuum-saugroboter-fehlermeldungen/
