### ISSUE TITLE
No vacuum cleaner is discovered.

### ISSUE THREAD

**Issue by Scream4Life** [nicoh88/homebridge-xiaomi-roborock-vacuum#38]
Hi, I can't find the error. Do you have any idea what is the cause of these error messages when homebridge is running?

ERR getBatteryLow | No vacuum cleaner is discovered.
ERR getSpeed | No vacuum cleaner is discovered.
ERR getCleaning | No vacuum cleaner is discovered.
ERR getDocked | No vacuum cleaner is discovered.
ERR getDevice | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong

`{
  "accessory": "XiaomiRoborockVacuum",
  "name": "Staubi",
  "ip": "ip-of-staubi",
  "token": "32-alphanumeric-code",
  "pause": false,
  "dock": true
 },
`

Token: I used the token months ago with an other plugin and it worked for some time. So I assume the token is correct. 

Vacuum Firmware 3.3.9_003466
NPM 6.7.0
Homebridge 0.4.46
node 8.15.0

**Comment by nicoh88** [comment]
Hmm, which model of xiaomi vaccum is it? 

Has you take a reset last months or connect it to another wifi? When yes, the token has changed.

**Comment by Scream4Life** [comment]
That was good hint. Indeed, the wifi has been changed a couple of times since that time. I'll go and try that and let you know.

**Comment by Scream4Life** [comment]
You can close this issue now. Didn't know under what circumstances this token changes. I thought it was something like a hardware id. Thank you for the quick help!
