### ISSUE TITLE
Saugroboter stellt sich auf Werkseinstellung zurück

### ISSUE THREAD

**Issue by maikburd** [nicoh88/homebridge-xiaomi-roborock-vacuum#4]
Nach einem reboot der homebridge (vermute ich mal) stellen sich meine beiden Saugroboter v1 auf die Werkseinstellung zurück.

**Comment by Nastras** [comment]
@nicoh88 Hier ist noch ein User betroffen:

http://forum.smartapfel.de/forum/thread/1374-homebridge-xiaomi-roborock-vacuum/?postID=27097#post27097

**Comment by Nastras** [comment]
Habe gerade auf die aktuelle Version aktualisiert jetzt habe ich auch diesen Fehler:

![529ccfff-9857-4e13-ba2b-6842f7ce7950](https://user-images.githubusercontent.com/27686185/37895043-6d6a5280-30e0-11e8-990e-a7abab3d66a6.jpeg)

**Comment by Nastras** [comment]
Nach einem Restart sieht es so aus, die Fehler Meldung ist auch noch da:
eprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Hier das log nach einem Restart:

Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] Connected to: 192.16xxxxx
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] Model: rockrobo.vacuum.v1
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] State: charging
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] BatteryLevel: 100
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] FanSpeed: 60
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] Serialnumber: 138xxxxxx
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] Firmwareversion: 3.3.9_003096
Mär 26 10:33:46 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:46] [Sauger Wohnzimmer] Number of state: 8
Mär 26 10:33:47 HomeBridgeServer homebridge[5981]: [2018-3-26 10:33:47] [Sauger Garage] ERORR GetDevice | No correct API answer from xiaomi/roborock
Mär 26 10:33:48 HomeBridgeServer homebridge[5981]: (node:5981) UnhandledPromiseRejectionWarning: undefined
Mär 26 10:33:48 HomeBridgeServer homebridge[5981]: (node:5981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Mär 26 10:33:48 HomeBridgeServer homebridge[5981]: (node:5981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nicoh88** [comment]
@Nastras mache bzgl. deines Problem bitte ein neues Issue auf.

@maikburd: Ich bin schon die letzten Tage auf der Suche nach dem Bug. Ich finde keine Grund. Meine Vermutung bisher, ist, dass sich der Saugroboter bei zu vielen API-Abfragen zurücksetzt. Habe deshalb den "Watchdog" von 10 Sekunden auf 30 Sekunden gestellt. Seit 2 Tagen bei mir keine Problem.

Hast du noch etwas anderes laufen, außer Homebridge? Zwei Homebridge vielleicht? Was die API-Abfragen somit verdoppeln würde? Oder was anderes was über miio, python-miio oder ähnliches deinen Saugroboter ansprechen könnte? Hast du ein benutzerdefiniertes Sprachpaket installiert?

**Jetzt wird es noch stranger...**
Ein Kumpel hat es gestern auch seinen Saugroboter zurückgesetzt, zu diesem Zeitpunkt war der RPi mit dem Homebridge-Plugin aber abgebaut und ausgeschaltet. Daher stochern ich momentan etwas im Dunklen. Langsam habe ich das Gefühl, dass es nicht im Plugin liegt, sondern Xiaomi rumspielt.

**Comment by Nastras** [comment]
Hey ho, ich habe doch diese Problem das der Token seit vorhin verschwunden ist. Stand doch in der Fehlermeldung die ich gepostet habe die du gelöscht hast. Wüsste nicht was ich sonst für ein Problem haben sollte 😄? 

Da steht doch keine Antwort von der API oder ist es was anderes?

![0436780d-cf85-4955-a7ff-1d4e3a523dca](https://user-images.githubusercontent.com/27686185/37901115-952af12a-30f0-11e8-9362-e6e6fdcb640a.jpeg)

**Comment by nicoh88** [comment]
@Nastras 

Du hast Rechte, habe zu viel gelöscht. 👎 

Ich meine bzgl. des **DEP0018**, sollst du entweder ein neues Issue auf machen oder in das existierende #3 reinschreiben. 

Ich bin an dem Problem dran, benötige aber eure Unterstützung um den Fehler zu finden! Wir müssen es erstmal weiter eingrenzen. Bitte ließ dir dazu meinen Eintrag (den vierten Eintrag) in diesem Issue durch.

Die Meldung aus deinem Screenshot besagt, dass er zu keiner Zeit deinen Saugroboter ansprechen konnte, vermutlich ist dein Roboter auf Werkseinstellungen zurückgesetzt. Du musst einen neuen Token auslesen.

Gruß Nico

**Comment by maikburd** [comment]
@nicoh88 Ich habe nichts anderes am laufen. Hatte vorher das homebridge-mi-robot_vacuum v0.1.2, da traten die Fehler nicht auf. Kann natürlich Zufall sein. Ich komme erst heute Abend dazu die Sauger  wieder einzubinden. Werde es dann nochmal mit dem alten Plugin versuchen und anschließend wieder zu deinem wechseln.

**Comment by Nastras** [comment]
Bei mir zu 
1. Nein
2. Nein
3. Nur das Standard Englisch Sprachpaket

> Langsam habe ich das Gefühl, dass es nicht am Plugin liegt, sondern Xiaomi rumspielt. Keine Ahnung

Habe vorhin mit einem Kumpel gesprochen der hatte vorhin auch das Problem das er der Sauger das Wifi nicht mehr gefunden hat und er auf Werkseinstellungen war. Und er benutzt nicht dein Plugin.

Ich habe zwei Sauger von Xiaomi bei mir hat sich einer von beiden verabschiedet bei dem ich noch denn Token auslesen muss.

Außerdem habe ich für meinen funktionierenden Sauger vorhin ein Firmware Update bekommen, könnte also gut sein das Xiaomi was im hintergrund macht.

**Comment by maikburd** [comment]
Also meiner hat sich soeben wieder verabschiedet. Nach einem Saugvorgang. Ich teste das jetzt mal ohne Homebridge Einbindung.

**Comment by nicoh88** [comment]
@maikburd Heute früh hat sich mein S50 auch verabschiedet, der V1 läuft noch, obwohl ich den aktuellen "doppelt" über die API penetriere - da ich aktuell entwickele.

**Wichtige Frage:** Hattest du mein Plugin oder wie gestern schon angekündigt "_homebridge-mi-robot_vacuum_" aktiv?

**Comment by maikburd** [comment]
@nicoh88 ich hatte dein Plugin, mit dem "homebridge-mi-robot_vacuum" ist meine Homebridge gecrasht. Gerade in der Sekunde ist mein Zweiter V1 verschwunden nach einem Saugvorgang. Ich hatte vorher schon dein Plugin deinstalliert und die Sauger aus der Config genommen, dann über Mi-App gestartet… zack… weg isser! hmmm? Ich bin ratlos.

**Comment by nicoh88** [comment]
Das ist alles sehr sehr eigenartig! 🔮 

Mich wundert, dass es in den Foren, keinen größeren Aufschrei gibt, wenn sich wirklich alle Roboter automatisch auf Werkseinstellungen zurücksetzen würden. Gerade von dehnen, die normale Anwender sind, ohne Homebridge oder ähnlichem.

Ich scheint fast so, als würde Xiaomi aktuell versuchen jede illegale Abfrage zu unterbinden, egal welches Plugin. Was nicht zu Xiaomi passen würde, da sie eigentlich für solche Entwicklungen offen sind... 😕 

PS: Ich schreibe aktuell das Plugin komplett neu, um die API-Abfrage, wie eigentlich vom [miio](https://github.com/aholstenson/miio) Entwickler gedacht, auf ein Minimum zu reduzieren. Ich hoffe dies löst unser Problem! Ich denke, ich bin heute Abend fertig.
Bin eigentlich auch kein Entwickler, versuche mich aber gerade auf diesem Gebiet, deswegen dauert es immer etwas länger - viel "_try and error_".

**Comment by maikburd** [comment]
"Es scheint fast so, als würde Xiaomi aktuell versuchen, jede illegale Abfrage zu unterbinden…" Sowas habe ich mir auch gedacht, mit neuem Token und ohne HB Einbindung sind beide durchgelaufen. Ich versuche gerade nochmals das "homebridge-mi-robot_vacuum" Plugin zu installieren, hatte gestern Abend nicht wirklich zeit, mich dem Fehler zu widmen. Mich wundert es auch ein bisschen, dass es anscheinen doch nicht so viele User "erwischt" hat. 

Bin gespannt auf dein Ergebnis.

@Nastras benutzt dein Kumpel aber ein anderes Plugin, oder läuft der Sauger bei ihm nativ?

**Comment by Nastras** [comment]
Er benutzt ein anderes Plugin. Welches von denn anderen beiden kann ich jetzt garnicht sagen. Aber das dürfte auch keine Rolle spielen.

Ich hatte oben geantwortet auf die frage ob andere Geräte noch miio nutzen nein, das war falsch hatte ganz vergessen das ich niüochndie Pflanzensensoren und meinen Ventilator von Xiaomi neu eingebunden habe. Bei mir ist gestern der Sauger Garage weg gewesen und später noch die Pflanzensensoren. Sauger Wohnbereich und Ventilator waren aber weiterhin noch vorhanden in HB.

So wirklich Sinn ergibt das alles nicht. Bin gespannt ob die neue Version da abhilfe schafft 😉

**Comment by Nastras** [comment]
Habe es jetzt seit 1 Std am laufen. Bisher sieht es ganz gut 👍
Ich melde mich morgen früh nochmal ob es irgendwelche Vorfälle gegeben hat.

**Comment by maikburd** [comment]
Ich werde das morgen Testen. Aber zur Info: Ich habe das "homebridge-mi-robot-vacuum" heute installiert. Habe es aber nur mit miio 0.14.1 zum laufen gebracht. Seit da keine Fehler, die Sauger sind etliche mal gelaufen und verweilen noch Netzwerk sowie in HomeKit ;-)

**Comment by Nastras** [comment]
Moin zusammen,
wollte nur kurz bescheid geben das seit dem Update bei mir keine Probleme mehr aufgetreten sind. Sieht also so aus das deine Arbeit sich gelohnt hat @nicoh88 
👍👍👍

**Comment by Bankaifan** [comment]
Hey, 
Vielleicht kann ich auch noch Infos beisteuern.
Ich hatte bis vorgestern das andere Vacuum-Plugin. Damit ist mir der Vacuum dann rausgeflogen. Deshalb bin ich auf dieses Plugin aufmerksam geworden.
Da hatte ich noch die Vorgängerversion vor 3.3.9_003194. Da ich eh den Token neu einlesen musste, habe ich dann heute das Update gemacht. 
Ich beobachte das mal weiter

**Comment by maikburd** [comment]
Läuft bis jetzt sehr gut, beide Sauger haben schon mehrere Fahrten hinter sich, ich bin sehr zuversichtlich 👍

**Comment by nicoh88** [comment]
Perfekt. Scheint nach dem ReWrite keine Probleme mehr zu geben. 👍
