### ISSUE TITLE
Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by scarry1992** [nicoh88/homebridge-xiaomi-roborock-vacuum#43]
[Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getDevice | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout.
wifi not changes, token same too. before all works as well. all packages version is last. What's wrong?

**Comment by nicoh88** [comment]
Do you have with the current version still problems?

**Comment by discostur** [comment]
@nicoh88 having the same error:

```
Jul 06 20:59:11 home.r.ringerl.de homebridge[10301]: [2019-7-6 8:59:11 PM] [Xiaomi Roborock S50] ERR getBatteryLow | No vacuum cleaner is discovered yet.
Jul 06 20:59:11 home.r.ringerl.de homebridge[10301]: [2019-7-6 8:59:11 PM] [Xiaomi Roborock S50] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul 06 20:59:34 home.r.ringerl.de homebridge[10301]: [2019-7-6 8:59:34 PM] [Xiaomi Roborock S50] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
``` 

miio version:

```
npm list -g miio
/usr/lib
└─┬ homebridge-xiaomi-roborock-vacuum@0.6.1
  └── miio@0.15.7-nicoh88  (git://github.com/nicoh88/miio.git#19e3660a4ed9cc4019b0ef887e432ea757eec922)
``` 

IP address and xiaomi token should be correct ... any ideas?

**Comment by backfisch88** [comment]
Try another Version. Like 0.50

**Comment by nicoh88** [comment]
Wrong token? Wrong IP?

**Comment by discostur** [comment]
sorry it was indeed the wrong IP address - my fault! everything working now ;)

**Comment by backfisch88** [comment]
To prevent a new ip, assign the roborock a static ip
