### ISSUE TITLE
Support for roborock s6?

### ISSUE THREAD

**Issue by olbura** [nicoh88/homebridge-xiaomi-roborock-vacuum#45]
Is the Model roborock.vacuum.s6 already supported? Tnx! 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/4757856/58834881-b5fad400-8654-11e9-8639-8db3e9fef6ba.png">

**Comment by nicoh88** [comment]
Nope. Unfortunately, no roborock.vacuum.s6 to test ...

**PRs Welcome** 👍

**Comment by backfisch88** [comment]
Will this Plugin support the s6?

**Comment by nicoh88** [comment]
Nope. Unfortunately, no roborock.vacuum.s6 to test ...

PRs Welcome 👍
