### ISSUE TITLE
Roborock s6

### ISSUE THREAD

**Issue by backfisch88** [nicoh88/homebridge-xiaomi-roborock-vacuum#47]
To add Support for the roborock s6 Just put this lines in the Folder For example usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/models.js

'roborock.vacuum.s6': Vacuum,

Under the line 
'roborock.vacuum.s5': Vacuum, 
(Line 44)

**Comment by nicoh88** [comment]
Backfisch? Deutsch oder? 🤪

Hast du den S6? Läuft so alles mit dem S6? Hast du es getestet?

Gruß Nico

**Comment by backfisch88** [comment]
Deutsch. Merkt man gar nicht oder 😂?

Habe den s6 und funktioniert. 

Dock Bewegungsmelder geht
Status der Sensoren
Pause Knopf 
Und der „Ventilator“ geht. 

Gibts sonst noch was zum Testen?

**Comment by backfisch88** [comment]
<a href="https://ibb.co/mGzxctQ"><img src="https://i.ibb.co/KXy1r7C/A0-D297-D0-28-CF-4745-A012-DA294-F199965.png" alt="A0-D297-D0-28-CF-4745-A012-DA294-F199965" border="0"></a>

**Comment by nicoh88** [comment]
Perfekt. Dann ändere ich das mal für alle! Dank Dir. 

Drehzahl ist auch einstellbar und je nach Drehzahl hört man während der Reinigung einen Unterschied?

iOS 13, cool läuft die Beta 1?

**Comment by backfisch88** [comment]
Befindet Drehzahl bin ich mir nicht sicher. Mache immer volle Kanne. Teste ich morgen nochmal. 

Ja bis auf die üblichen bugs läuft es super :)

**Comment by backfisch88** [comment]
Kurzes Update. Drehzahl funktioniert. Allerdings ist 100% = Standard und nicht maximal.

**Comment by nicoh88** [comment]
> Allerdings ist 100% = Standard und nicht maximal.

Hmm, das müssen wir genauer prüfen... 
Auch beim Gen1 und Gen2 gibt es Unterschiede was die Stufen / Modi angeht.
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L22-L42

Am einfachsten wäre: Debug-Log aktivieren, Log Live (`tail -f` / `journalctl -f`) anschauen, dann über die Xiaomi App, Stufe A auswählen und bis zu 30 Sekunden warten, welcher Wert in der Log auftaucht. Das mit jeder Stufe und dann hier die Erkenntnisse posten. 😄 

Danke und Gruß Nico

**Comment by backfisch88** [comment]
Ich tippe mal, dass es ähnlich ist wie bei gen1, da bei gen1 das mopping dazu kommt. Das gibt es bei s6 nicht. Aber ich werde morgen berichten 🤘🏼

**Comment by backfisch88** [comment]
Alsooo
Max: [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 104%
Turbo : [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 103%
Standard : [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 102%
Leise : [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 101%

**Comment by backfisch88** [comment]
2019, 11:16:30 AM] [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 101%
Jun 15 11:16:30 raspberrypi homebridge[763]: [6/15/2019, 11:16:30 AM] [Dieter] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 101%, this speed is not supported
Jun 15 11:17:00 raspberrypi homebridge[763]: [6/15/2019, 11:17:00 AM] [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 102%
Jun 15 11:17:00 raspberrypi homebridge[763]: [6/15/2019, 11:17:00 AM] [Dieter] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 102%, this speed is not supported
Jun 15 11:17:30 raspberrypi homebridge[763]: [6/15/2019, 11:17:30 AM] [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 103%
Jun 15 11:17:30 raspberrypi homebridge[763]: [6/15/2019, 11:17:30 AM] [Dieter] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 103%, this speed is not supported
Jun 15 11:18:00 raspberrypi homebridge[763]: [6/15/2019, 11:18:00 AM] [Dieter] MON changedSpeed | roborock.vacuum.s6 | FanSpeed is now 104%
Jun 15 11:18:00 raspberrypi homebridge[763]: [6/15/2019, 11:18:00 AM] [Dieter] WAR changedSpeed | roborock.vacuum.s6 | Speed was changed to 104%, this speed is not supported

**Comment by nicoh88** [comment]
Perfekt - das kriegen wir doch hin. 😀
Kümmere mich kommende Woche darum. 

Melde mich bzgl. BETA-Test. 👍

Gruß

**Comment by backfisch88** [comment]
Super! 👍 vielen Dank für das schnelle Feedback

**Comment by nicoh88** [comment]
Soooo...

Fanspeed levels:
* Off (0%)
* Quiet (1-38%)
* Balanced (39-60%)
* Turbo (61-77%)
* Max Speed (78-100%)

Bitte aktuelle Master-Version testen. 👍 

`npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm`

**Comment by backfisch88** [comment]
Funktioniert nicht. 
Bekomme im log folgende Meldungen 

Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Dieter] INF getCleaning | roborock.vacuum.s6 | Cleaning is true
Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Dieter] INF getSpeed | roborock.vacuum.s6 | Fanspeed is 102
Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Dieter] INF getBatteryLow | roborock.vacuum.s6 | Batterylevel is 98%
Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Dieter] INF getPauseState | roborock.vacuum.s6 | Pause possible is true
Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Bathroom Vacuum Running Twice] INF getBatteryLow | roborock.vacuum.s6 | Batterylevel is 98%
Jun 17 11:02:12 raspberrypi homebridge[11819]: [6/17/2019, 11:02:12 AM] [Bathroom Vacuum Running Twice] INF getCleaning | roborock.vacuum.s6 | Cleaning is false
Jun 17 11:02:13 raspberrypi homebridge[11819]: [6/17/2019, 11:02:13 AM] [Dieter] ACT setSpeed | roborock.vacuum.s6 | FanSpeed set to 60 over miIO.
Jun 17 11:02:13 raspberrypi homebridge[11819]: [6/17/2019, 11:02:13 AM] [Dieter] ACT setSpeed | roborock.vacuum.s6 | FanSpeed set to 60 over miIO.
Jun 17 11:02:21 raspberrypi homebridge[11819]: [6/17/2019, 11:02:21 AM] [Bathroom Vacuum Running Twice] MON changedCharging | roborock.vacuum.s6 | ChargingState is now false
Jun 17 11:02:21 raspberrypi homebridge[11819]: [6/17/2019, 11:02:21 AM] [Bathroom Vacuum Running Twice] INF changedCharging | roborock.vacuum.s6 | Charging is cancelled
Jun 17 11:02:21 raspberrypi homebridge[11819]: [6/17/2019, 11:02:21 AM] [Bathroom Vacuum Running Twice] INF changedCleaning | roborock.vacuum.s6 | Cleaning is ON.





Er zeigt an, dass er es ändert, ändert es aber nicht. Also er zeigt 90, 38 an (also geht übern Regler)
Beim Ausfahren ausm dock steht auch, dass

**Comment by nicoh88** [comment]
... habe was gefunden! Und nochmal...

`npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm`

**Comment by backfisch88** [comment]
PERFEKT! Wie Neu!

Einzige was ich jetzt noch habe... er fährt nicht immer ins Dock bei 0%. 
Als Reaktion bekommt man vom Roboter die Ansage: Grundreiniging 🙈😂

Jun 17 11:19:53 raspberrypi homebridge[12643]: [6/17/2019, 11:19:53 AM] [Dieter] ACT setCleaning | roborock.vacuum.s6 | Stop cleaning and go to charge.
Jun 17 11:19:54 raspberrypi homebridge[12643]: [6/17/2019, 11:19:54 AM] [Dieter] INF changedPause | roborock.vacuum.s6 | Paused not possible, no cleaning
Jun 17 11:20:02 raspberrypi homebridge[12643]: [6/17/2019, 11:20:02 AM] [Dieter] INF changedCleaning | roborock.vacuum.s6 | Cleaning is OFF.
Jun 17 11:20:02 raspberrypi homebridge[12643]: [6/17/2019, 11:20:02 AM] [Dieter] INF changedPause | roborock.vacuum.s6 | Paused not possible, no cleaning


Ist wie gesagt nicht immer 

Sonst aber perfekt. Danke!

**Comment by nicoh88** [comment]
Perfekt. Das lassen wir so. Kommt eh nie vor. 😄

**Comment by nicoh88** [comment]
Version 0.5.1 veröffentlich.

Kannst wieder offiziell aus NPM installieren:
npm install -g --unsafe-perm homebridge-xiaomi-roborock-vacuum@latest

**Comment by nicoh88** [comment]
Wenn @afharo irgendwann mal Zeit hat, macht er bestimmt den Code noch hübsch. 👍 Bin kein JS-Experte. Danke

Danke an @backfisch88 für die Infos zum S6.

**Comment by backfisch88** [comment]
Jein. Lasse bei Ankunft zurück zur Station fahren. Da ging es komischerweise bisher immer. Nur wenn man das manuell setzt nicht. Egal.
Danke für die Mühe! ❤️❤️

**Comment by nicoh88** [comment]
Höh, da setzt du doch aber nicht auf 0% oder? 
Sondern machst ihn einfach per Touch auf die Kachel aus? 

Vielleicht war es nur "_einmalig_". Bitte beobachten und ggf. nochmal melden.

**Comment by backfisch88** [comment]
Ja normal schon. Bei iOS 13 geändert ;) deswegen sage ich ja... automatisch per Szene geht das. Kann auch n iOS 13 bug sein. Da passiert beim Touch auf die Kachel nämlich die zusammen Fassung vom Gerät (wie oben auf dem Screenshot) 
Per Szene kann man das nämlich auf „deaktivieren“ setzen. 
Also lassen wir so und warten bis Herbst 😂

**Comment by nicoh88** [comment]
Hmm, hier kannst du nicht an-/ausschalten?

![68747470733a2f2f692e6962622e636f2f4b5879317237432f](https://user-images.githubusercontent.com/264264/59597820-0402e380-90fb-11e9-8b17-346d8edeacdd.jpg)

**Comment by backfisch88** [comment]
Das ist der Pause Schalter. 
Unten der Dock Bewegungsmelder
Und links der normale Ventilator

**Comment by nicoh88** [comment]
Ach Gott. Stimmt. Mein Fehler.

Aber ein komisches Verhalten, dass es mal funktioniert und mal nicht. Bitte beobachten, ob der Fehler mit zukünftigen Betas bestehen bleibt.

**Comment by nicoh88** [comment]
Hi @backfisch88,

wir haben nochmal was an der Drehgeschwindigkeits-Logik gedreht. 🤣 
Würdest du die aktuelle Master-Version nochmal testen.

`npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm`

Danke

**Comment by backfisch88** [comment]
Mach ich später. Bin unterwegs :)

**Comment by backfisch88** [comment]
Funktioniert!
Und das beste ist! Das zur Ladestation fahren funktioniert 🤘🏼😂
