### ISSUE TITLE
Some feature ideas

### ISSUE THREAD

**Issue by mangerlahn** [nicoh88/homebridge-xiaomi-roborock-vacuum#49]
First of all, thank you so much for this plugin! 

Now that I've lived with this HomeKit integration for a couple of months, I started to generate some ideas on how this _could_ be extended. I would dump these ideas here, if you care for one or more of these, I can create proper issues afterwards 😉. 

I really like the map that is generated during cleanup. I also know that these maps are lying around somewhere on the robot. Maybe we could extend the Dock sensor thingy with the IP-Camera accessory and feed that with either the live map or the finished cleanup. 
It'd be easier to find the robot if it dies in the middle of the cleaning process that way.

The thing is that I don't really get yet how this HomeKit stuff is structured. I know that the bridge is connected to accessories. All of which have several characteristics. But I don't really know how these can be combined. I am not super happy about having one robot, but 3 buttons in HomeKit. I have seen other accessories that combine functionality, like the fan and the on/off switch into one accessory. However I don't know if that is possible with Homebridge, or if I just do something wrong on my side here. 

The last thing would require quite some work for each user, but this could be super convenient. It'd be fun to be able to define switches for spot cleaning with the associated coordinates so that one could have a switch in every HomeKit room. After activating that switch, the robot would then spot-clean just that room. Add Siri to the game and you get some real magic there 😉

**Comment by mitch7391** [comment]
On your second note, I am hoping that with ios13 it will group all three ‘buttons’ together, like I have seen for other devices in previews.

I would really love to zone cleaning integrated into this plugin. The people using HA have been able to use the coordinates of zones on the map to designate zoned rooms and can activate a clean in the bedroom for example.

**Comment by mangerlahn** [comment]
Great to see this in iOS 13!
I saw some EVE thermostat thingy that had a temperature slider but also a mode button to switch the thing off. But if iOS 13 does this for us, then that is no concern anymore

**Comment by backfisch88** [comment]
Your dream will become true;)

<a href="https://ibb.co/z83zp1N"><img src="https://i.ibb.co/N10M5X7/85-F3-ADCD-768-B-4-AC7-8290-F86478-CA5-BAA.png" alt="85-F3-ADCD-768-B-4-AC7-8290-F86478-CA5-BAA" border="0"></a>
