### ISSUE TITLE
Roborock S6 | standby?! | sometimes starts only on the second try

### ISSUE THREAD

**Issue by backfisch88** [nicoh88/homebridge-xiaomi-roborock-vacuum#50]
Hi 

Habe noch was festgestellt. 
Ich lasse meinen Roboter bei Abwesenheit fahren ODER täglich um 17 Uhr. Habe dafür n Fakeschalter gemacht, der halt an geht sobald er losfährt. Also alle sind weg - 30 Minuten läuft auf - Staubsauger an, fakeschalter an 
Und 17 Uhr - wenn Fake Schalter aus dann - Staubsauger an, Fake Schalter an
(Wird um 0 Uhr wieder aus gestellt der Fake Schalter)

Soweit so gut. Habe jetzt festgestellt, dass es nicht funktioniert. Nichtmal immer mit der Testfunktion von Home (Fake Schalter geht an aber Roboter macht nix, wenn man das wiederholt gehts, sprich Standby.)
 Und zwar immer nach ca 2 Stunden. 
Gehen die Roboter nach einer Zeit in den Standby?! Lasse den Roboter jetzt einfach mal minütlich anpingen. Vielleicht bringt es was (werde berichten)

**Comment by backfisch88** [comment]
Also das pingen hat nichts gebracht. Muss ihn praktisch 2 mal starten lassen (manuell gehts) automatisch nicht 💁🏼‍♂️🤦🏼‍♂️

**Comment by nicoh88** [comment]
Was sagt die Homebridge Log? Irgendwann müsste es ja eine Fehlermeldung kommen.

**Comment by nicoh88** [comment]
@afharo

does the reconnection function not recognize in the background whether the connection must be rebuilt? Special only after a faulty start attempt on homekit?

**Comment by backfisch88** [comment]
Da muss ich nochmal bis später warten. Der muss ja erst mal wieder in den Standby gehen :)

**Comment by backfisch88** [comment]
3/2019, 6:50:02 PM] [Dieter] ACT setSpeed | roborock.vacuum.s6 | FanSpeed set to 104 over miIO for "Max".
Jun 23 18:50:12 raspberrypi homebridge[25722]: [6/23/2019, 6:50:12 PM] [Dieter] ACT setSpeed | roborock.vacuum.s6 | FanSpeed set to 104 over miIO for "Max".


Beim 2. mal fährt er.

**Comment by backfisch88** [comment]
Hab es jetzt nochmal probiert. Jetzt fährt er gar nicht über ne Automatik 🤔 wenn ich den Lüfter manuell an mache gehts 

Log zum manuellen an machen 

borock.vacuum.s6 | Batterylevel is 100%
Jun 23 18:54:53 raspberrypi homebridge[25722]: [6/23/2019, 6:54:53 PM] [Dieter] INF getDocked | roborock.vacuum.s6 | Robot Docked is false (Status is cleaning)
Jun 23 18:54:53 raspberrypi homebridge[25722]: [6/23/2019, 6:54:53 PM] [Dieter] ACT setSpeed | roborock.vacuum.s6 | FanSpeed set to 0 over miIO for "Off".

**Comment by backfisch88** [comment]
Und als Anmerkung. Das hat vor dem Update (also 0.50) vor der s6 Unterstützung funktioniert 🤨

**Comment by backfisch88** [comment]
Mach dir erst mal keine Arbeit. Ich teste das weiter. Habe mal den kompletten pi neu gestartet und 20 mal die homebridge jetzt gehts. Es scheint zumindest so 

Ich melde mich, ob er morgen in Abwesenheit fährt :)

**Comment by nicoh88** [comment]
Hi @backfisch88,

ich glaube, dass es sich um ein Kompatibilitätsproblem mit dem Roborock S6 handelt. Da scheinen ca. 1/3 der Startvorgänge einfach ins Nirvana zu laufen. Keine Ahnung, warum. 

Mit dem Gen 1 und Gen 2 habe ich hier keinerlei Probleme - alles 1A.

Wenn die Probleme weiterhin bestehen, muss mir mal jemand von euch ein S6 "_FREI HAUS_" schicken, damit ich mir das Problem mal genauer anschauen kann. 🤣 

@iAmRenzo beschreibt [hier](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/53#issuecomment-504754024) ein ähnliches Problem:

> I hope that the issue of not activating on first try is fixed now. I always needed to tick the vacuum, switch it off and then again on in the home app to let him do his job.

@iAmRenzo iOS 13?

**Comment by backfisch88** [comment]
Nach einem Neustart funktioniert es bis jetzt! Ich werde morgen berichten :)

**Comment by afharo** [comment]
https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/50#issuecomment-504755293

AFAIK, the connection should be the same no matter if it’s during the startup or somewhen in a long time running. It tries to reach the socket element from the device (the `miio` library throws an error if the socket has been destroyed at any point), then re-enforces the reconnection.

Regarding polling, it’s automatically done by the miio library every second.

**Comment by backfisch88** [comment]
Alsoooo
Der Staubsauger fährt immer noch nach dem 1. mal los. 
Kannst das Thema von meiner Seite aus schließen. 

Neustart hat das Problem prinzipiell gelöst

**Comment by backfisch88** [comment]
![Image](https://i.imgur.com/0CWtW6d.jpg)

Also Automatik geht 🤘🏼 ist jetzt fast nach 12 Stunden selbstständig angelaufen

**Comment by iAmRenzo** [comment]
I am not on iOS 13 no, I have the roborock first generation. Have not tried it with the new plugin version (I installed yesterday).

**Comment by backfisch88** [comment]
Is the normal xiaomi Home App From AppStore

**Comment by iAmRenzo** [comment]
@backfisch88 it looks that everybody has a slightly different app. Probably depending on which country you selected? I don't have those colours. 

Anyway, now on iOS 13 but the plugin still doesn't work.... :(
