### ISSUE TITLE
Zoned Cleaning

### ISSUE THREAD

**Issue by mitch7391** [nicoh88/homebridge-xiaomi-roborock-vacuum#51]
First of all, love this plugin and love your work on it so far.

I would really love to see zone cleaning integrated into this plugin. The people using HA have been able to use the coordinates of zones on the map to designate zoned rooms and can activate a clean in the bedroom for example.

I am wondering if we can get this added to the plugin and integrate it into the config.json file by entering the coordinates into the config for each room. Then a button can be pressed on HomeKit or Siri can be used to initiate a clean for that one room only. Love to hear your thoughts :)

**Comment by mangerlahn** [comment]
Would love to see this. Thought of the same implementation :).

I think the hardest part for the user would be to figure out the coordinates with trial and error, since the coordinates are not exposed within the map.. 
But hey,  you do that once and then its fine :)

**Comment by afharo** [comment]
I think it’s a great feature! And would love to play around with any option should we can provide some sort of UI to see the map and select the coordinates (the user will need to find out the coordinates any how, either via logs or a UI, but need to grab them somehow).
I saw some other Xiaomi-Homebridge libraries already providing the zones configuration. Might worth a check about how they’re doing so. But I recall when reading them, they were claiming issues with the robot suddenly changing the orientation of the map and the coordinates not being valid anymore.
But if it works most of the time and the user is aware it might happen, all good from my point of view.

Anyone can help creating a PR?
I can give it a try in a couple of weeks. I’m away for a while and won’t be able to jump on coding anytime soon.

Hopefully, the public beta of iOS 13 is out by then and I’ll get to test it there (maybe using some new capabilities) :)

**Comment by nicoh88** [comment]
Example fork:
https://github.com/Smileydude/homebridge-xiaomi-roborock-vacuum/

Not merged, not optional.
