### ISSUE TITLE
roborock.vacuum.t6 | No vacuum cleaner is discovered yet

### ISSUE THREAD

**Issue by pymylx** [nicoh88/homebridge-xiaomi-roborock-vacuum#52]
hi there,
i just getting the error when i starting hombridge after i put my Roborock Vacuum s6 to config.json, could you help me pls?
thanks
![image](https://user-images.githubusercontent.com/52126354/59975150-61a99b00-95e7-11e9-9355-67f12c37be57.png)
![image](https://user-images.githubusercontent.com/52126354/59975158-72f2a780-95e7-11e9-9e60-bb43d02f9949.png)
![image](https://user-images.githubusercontent.com/52126354/59975171-961d5700-95e7-11e9-96bf-c76cb6945a53.png)

**Comment by nicoh88** [comment]
Which version has you installed?

**Comment by nicoh88** [comment]
Try:

```
sudo su -
npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
```

`sudo su -` is important

**Comment by pymylx** [comment]
> Which version has you installed?
> 
> `npm list --depth=0 -g | grep -i roborock`
> 
> 0.6.0 is the version with s6 support.
> 
> —
> 
> Try:
> 
> ```
> sudo su -
> npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
> ```
> 
> `sudo su -` is important

I already using the latest version
![image](https://user-images.githubusercontent.com/52126354/59977642-40a47280-9606-11e9-9329-f5dcbc6d9000.png)

**Comment by nicoh88** [comment]
hmm. strange.

Which model name appears, if you hang an `info` behind your `mirobo` command?

`mirobo` command execute on the same system as homebridge?

**Comment by nicoh88** [comment]
@backfisch88: Welche Firmware hast du auf deinem S6?

**Comment by backfisch88** [comment]
Die aktuellste 
3.4.5_0500

**Comment by backfisch88** [comment]
{
            "name": "Dieter",
            "ip": "192.168.178.48",
            "token": "77746e6b766e696649796c646a656f68",
            "pause": true,
            "dock": true,
            "accessory": "XiaomiRoborockVacuum"
        },

As Working sample :)

**Comment by backfisch88** [comment]
Is the roborock connected to the App?

**Comment by pymylx** [comment]
> mirobo
The vision is v3.4.5_0500, same as @backfisch88 , but the model is roborock.vacuum.t6(in China the model called T6 instead of s6), I'm not sure is that the problem? Also I'm already connected to the MI app.
![image](https://user-images.githubusercontent.com/52126354/59981179-86773000-9632-11e9-8cfa-867d0c8c9b7e.png)

**Comment by afharo** [comment]
Can you please double check the installed miio library? `npm list -g miio`

**Comment by pymylx** [comment]
The miio library will be like that
![image](https://user-images.githubusercontent.com/52126354/59982290-5f285f00-9642-11e9-879d-d834d0eb2373.png)

**Comment by backfisch88** [comment]
The t6 is the non EU Model i think. 

@nico i think you Must add this to the miiio Library

**Comment by nicoh88** [comment]
@pymylx 

- miio library updated
- support for roborock t6, same s6, added

please test the github master version:

```
sudo su -
npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm
```

thanks for feedback 🥇

**Comment by backfisch88** [comment]
S6 works perfectly already

**Comment by nico** [comment]
> @nico i think you Must add this to the miiio Library

Why should I add this to the miiio library?

**Comment by pymylx** [comment]
> @pymylx
> 
> * miio library updated
> * support for roborock t6, same s6, added
> 
> please test the github master version:
> 
> ```
> sudo su -
> npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm
> ```
> 
> thanks for feedback 🥇

Thanks a lot ,it finally worked!!!

**Comment by suxus-zz** [comment]
Hello
I have also the same problem 

ERR getDevice | Is not a vacuum cleaner!
No vacuum cleaner is discovered

And this ist my miio output.

`
pi@raspberrypi:~ $ npm list -g miio
/usr/local/lib
├─┬ homebridge-xiaomi-roborock-vacuum@0.6.4
│ └── miio@0.15.8-nicoh88  (git://github.com/nicoh88/miio.git#4a126d3a13a05035c057777442a2ae36e9977a13)
├─┬ homebridge-xiaomi-roborock-vacuum-zones@0.4.2
│ └── miio@0.15.4  (git://github.com/Smileydude/miio.git#4279bba6a0349d1bb794185e7aab9d85a605f44c)
└── miio@0.15.6 
`

I don't know what's the problem

Thank you very much for the help.
Greeting
