### ISSUE TITLE
Button statt Ventilator

### ISSUE THREAD

**Issue by dominiksahli** [nicoh88/homebridge-xiaomi-roborock-vacuum#54]
Mein Roborock S6 wird als Button statt als Ventilator angezeigt und kann nicht gesteuert werden. Was kann ich tun?
![9D9ED5F4-3195-4FB0-A362-5E77925B456C](https://user-images.githubusercontent.com/48891906/60137395-09b99280-97a7-11e9-9d7c-9250f3f2b6bb.png)

**Comment by backfisch88** [comment]
Probiere mal die homebridge komplett vom Strom zu nehmen und neu starten. Vielleicht schafft das Abhilfe

**Comment by dominiksahli** [comment]
Das hat leider nicht geholfen. Werde die Homebridge mal neu aufsetzen.

**Comment by backfisch88** [comment]
Mal so als Tipp!
Ich hab am Anfang (weil einfach) die HB über diese App aufgesetzt. 
Hab das angefangen manuell zu machen. Ist wesentlich stabiler. 
https://forum.smartapfel.de/forum/thread/197-homebridge-image-raspbian-stretch-lite-raspberry-pi/
Hab es dadrüber gemacht. Das funktioniert wirklich gut 

Hatte über die App nämlich immer komische Fehler

**Comment by dominiksahli** [comment]
Besten Dank für den Tipp.
Schlussendlich löste simples Löschen und erneutes Hinzufügen der Homebridge in der Home-App das Problem.
