### ISSUE TITLE
Automation klappt nicht 

### ISSUE THREAD

**Issue by backfisch88** [nicoh88/homebridge-xiaomi-roborock-vacuum#55]
Hallo ich mal wieder 🤪

Habe das bezüglich des Standby (vorheriges Thema) nochmal getestet. 
Egal nach welcher Zeit 
Manuell geht immer an
Automation nicht immer. 50:50 Chance 
Idee woran das hängen kann?! 
Am Plugin eher weniger oder?

Als Info. Die Aktion wird ausgeführt (also der Staubsauger geht Software seitig an). Staubsauger reagiert nicht. Und geht dann im HomeKit wieder aus. 
Werde es morgen nochmal probieren ihn an aus an aus an zu schalten. Vielleicht bringt das was 🤔
Im log steht zwar, dass MIOO das
Ding hochfährt, der Roboter selber reagiert aber nicht. Sehr seltsam

**Comment by nicoh88** [comment]
Eigenartig. Scheint ein T6/S6 Bug zu sein. 
Weiterhin Probleme? Schon was neues rausgefunden?

Habe hier mit dem Gen1 und Gen2, welchen jeden Tag über HomeKit um 8:40 starten, kein Problem.

Gruß Nico

**Comment by backfisch88** [comment]
Habe seit Neustart auch keine Probleme mehr. 

Closed
