### ISSUE TITLE
Homebridge verliert Roborock Verbindung

### ISSUE THREAD

**Issue by exuded** [nicoh88/homebridge-xiaomi-roborock-vacuum#56]
Hallo Nicoh,

vielen Dank erstmal für deine Arbeit dieses Plugin für den Roborock zu erstellen. 
Es läuft auch eigentlich ganz gut, allerdings gibt es nach einiger Zeit Verbindungsverluste zum Roboter, die dann dazu führen, dass Homebridge gar nicht mehr läuft und auch die anderen Plugins nicht mehr funktionieren.
Anbei sende ich mal den Log Auszug:
`pi@raspi1:~ $ sudo tail -100 /var/log/syslog
Jul  7 14:00:59 raspi1 homebridge[386]: #033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m
Jul  7 14:00:59 raspi1 homebridge[386]: #033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m
Jul  7 14:00:59 raspi1 homebridge[386]: #033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m
Jul  7 14:00:59 raspi1 homebridge[386]: #033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[40m  #033[0m#033[47m  #033[0m
Jul  7 14:00:59 raspi1 homebridge[386]: #033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m#033[47m  #033[0m
Jul  7 14:00:59 raspi1 homebridge[386]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Jul  7 14:00:59 raspi1 homebridge[386]:                        
Jul  7 14:00:59 raspi1 homebridge[386]:     ┌────────────┐
Jul  7 14:00:59 raspi1 homebridge[386]:     │ 031-45-154 │
Jul  7 14:00:59 raspi1 homebridge[386]:     └────────────┘
Jul  7 14:00:59 raspi1 homebridge[386]:                        
Jul  7 14:00:59 raspi1 homebridge[386]: [2019-7-7 14:00:59] Homebridge is running on port 51826.
Jul  7 14:01:00 raspi1 com.teamviewer.TeamViewer[614]: QSystemTrayIcon::setVisible: No Icon set
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: CurrentPosition for DUOFERN_401140-position
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 100 (as number)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: TargetPosition for DUOFERN_401140-position
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 100 (as number)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: PositionState for DUOFERN_401140-moving
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 2 (as number; means STOPPED)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: CurrentPosition for DUOFERN_493AA0-position
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 100 (as number)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: TargetPosition for DUOFERN_493AA0-position
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 100 (as number)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM] query: PositionState for DUOFERN_493AA0-moving
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [FHEM]   cached: 2 (as number; means STOPPED)
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getCleaning | No vacuum cleaner is discovered yet.
Jul  7 14:01:02 raspi1 homebridge[386]: [2019-7-7 14:01:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:01:04 raspi1 homebridge[386]: [2019-7-7 14:01:04] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
Jul  7 14:01:28 raspi1 systemd[1]: Time has been changed
Jul  7 14:01:28 raspi1 systemd-timesyncd[270]: Synchronized to time server 178.63.9.110:123 (1.de.pool.ntp.org).
Jul  7 14:01:28 raspi1 systemd[564]: Time has been changed
Jul  7 14:01:28 raspi1 systemd[1]: apt-daily.timer: Adding 2h 8min 27.110776s random time.
Jul  7 14:01:28 raspi1 systemd[1]: apt-daily-upgrade.timer: Adding 24min 19.733702s random time.
Jul  7 14:01:33 raspi1 unifi.init[387]: Starting Ubiquiti UniFi Controller: unifi.
Jul  7 14:01:33 raspi1 systemd[1]: Started unifi.
Jul  7 14:01:33 raspi1 systemd[1]: Reached target Multi-User System.
Jul  7 14:01:33 raspi1 systemd[1]: Reached target Graphical Interface.
Jul  7 14:01:33 raspi1 systemd[1]: Starting Update UTMP about System Runlevel Changes...
Jul  7 14:01:33 raspi1 systemd[1]: Started Update UTMP about System Runlevel Changes.
Jul  7 14:01:33 raspi1 systemd[1]: Startup finished in 1.414s (kernel) + 38.293s (userspace) = 39.707s.
Jul  7 14:02:21 raspi1 systemd[1]: Started Session c3 of user pi.
Jul  7 14:02:36 raspi1 crontab[1148]: (root) BEGIN EDIT (root)
Jul  7 14:03:29 raspi1 homebridge[386]: [2019-7-7 14:03:29] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
Jul  7 14:03:44 raspi1 crontab[1148]: (root) REPLACE (root)
Jul  7 14:03:44 raspi1 crontab[1148]: (root) END EDIT (root)
Jul  7 14:04:53 raspi1 homebridge[386]: [2019-7-7 14:04:53] [FHEM] query: TargetPosition for DUOFERN_493AA0-position
Jul  7 14:04:53 raspi1 homebridge[386]: [2019-7-7 14:04:53] [FHEM]   cached: 100 (as number)
Jul  7 14:04:53 raspi1 homebridge[386]: [2019-7-7 14:04:53] [FHEM] query: CurrentPosition for DUOFERN_493AA0-position
Jul  7 14:04:53 raspi1 homebridge[386]: [2019-7-7 14:04:53] [FHEM]   cached: 100 (as number)
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getSpeed | No vacuum cleaner is discovered yet.
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getCleaning | No vacuum cleaner is discovered yet.
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getBatteryLow | No vacuum cleaner is discovered yet.
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getDocked | No vacuum cleaner is discovered yet.
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [FHEM] query: TargetPosition for DUOFERN_401140-position
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [FHEM]   cached: 100 (as number)
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [FHEM] query: CurrentPosition for DUOFERN_401140-position
Jul  7 14:05:02 raspi1 homebridge[386]: [2019-7-7 14:05:02] [FHEM]   cached: 100 (as number)
Jul  7 14:05:31 raspi1 homebridge[386]: [2019-7-7 14:05:31] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [FHEM] query: TargetPosition for DUOFERN_401140-position
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [FHEM]   cached: 100 (as number)
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [FHEM] query: CurrentPosition for DUOFERN_401140-position
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [FHEM]   cached: 100 (as number)
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getSpeed | No vacuum cleaner is discovered yet.
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getCleaning | No vacuum cleaner is discovered yet.
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getBatteryLow | No vacuum cleaner is discovered yet.
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getDocked | No vacuum cleaner is discovered yet.
Jul  7 14:06:06 raspi1 homebridge[386]: [2019-7-7 14:06:06] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:14 raspi1 homebridge[386]: [2019-7-7 14:07:14] [FHEM] query: TargetPosition for DUOFERN_493AA0-position
Jul  7 14:07:14 raspi1 homebridge[386]: [2019-7-7 14:07:14] [FHEM]   cached: 100 (as number)
Jul  7 14:07:14 raspi1 homebridge[386]: [2019-7-7 14:07:14] [FHEM] query: CurrentPosition for DUOFERN_493AA0-position
Jul  7 14:07:14 raspi1 homebridge[386]: [2019-7-7 14:07:14] [FHEM]   cached: 100 (as number)
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getSpeed | No vacuum cleaner is discovered yet.
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getCleaning | No vacuum cleaner is discovered yet.
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getBatteryLow | No vacuum cleaner is discovered yet.
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getDocked | No vacuum cleaner is discovered yet.
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [FHEM] query: CurrentPosition for DUOFERN_401140-position
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [FHEM]   cached: 100 (as number)
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [FHEM] query: TargetPosition for DUOFERN_401140-position
Jul  7 14:07:17 raspi1 homebridge[386]: [2019-7-7 14:07:17] [FHEM]   cached: 100 (as number)
Jul  7 14:07:33 raspi1 homebridge[386]: [2019-7-7 14:07:33] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
Jul  7 14:09:28 raspi1 homebridge[386]: [2019-7-7 14:09:28] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
Jul  7 14:09:28 raspi1 homebridge[386]: [2019-7-7 14:09:28] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
Jul  7 14:09:35 raspi1 homebridge[386]: [2019-7-7 14:09:35] [Xiaomi Roborock S50 Vaccum 2nd Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

**Comment by nicoh88** [comment]
Hi,

mit Logauszug kann man nichts anfangen. Die ganze Formatierung ist für den Arsch! 😕 

Falscher Token? Falsche IP? 

Bitte mit `mirobo` prüfen:
https://github.com/rytilahti/python-miio

**Comment by backfisch88** [comment]
Habe das seit vorgestern auch! Habe auf Node 8.16.0 gedowngraded. Plugin deinstalliert. Reboot. Installiert. Scheint wieder zu gehen

**Comment by exuded** [comment]
Ich habe beobachtet, dass der Roborock sich gerne mal eine neue IP in meinem DHCP Netzwerk geben lässt. Habe das Netzwerk nun so konfiguriert, dass der Robo immer die gleiche IP bekommt. Bisher klappt es wieder. Ich werde beobachten.
