### ISSUE TITLE
S6 not returning to dock

### ISSUE THREAD

**Issue by ludgats** [nicoh88/homebridge-xiaomi-roborock-vacuum#57]
Everything works great except when turning off the vacuum it says “stop cleaning” and just stays in place. I’ve tested with the s50 and it returned to the base. Finishing the clean also returns it to the base.

**Comment by nicoh88** [comment]
Close?

**Comment by DmitryApollonov** [comment]
Hi! The problem is actual for S6. It just stops cleaning.

**Comment by dadada3000** [comment]
I think that need to add a short pause between 2 commands: app_stop and app_charge.
I just copy charge call in miio/lib/devices/vacuum.js 
...
`activateCharging() {
		return this.call('app_stop', [])
			.then(checkResult)
			.then(() => this.call('app_charge', [], {
				refresh: [ 'state' ],
				refreshDelay: 1000
			}))
.then(() => this.call('app_charge', [], {
                                refresh: [ 'state' ],
                                refreshDelay: 1000
                        }))
			.then(checkResult);
	}
`
...

**Comment by dadada3000** [comment]
> I think that need to add a short pause between 2 commands: app_stop and app_charge.
> I just copy charge call in miio/lib/devices/vacuum.js
> ...
> `activateCharging() { return this.call('app_stop', []) .then(checkResult) .then(() => this.call('app_charge', [], { refresh: [ 'state' ], refreshDelay: 1000 })) .then(() => this.call('app_charge', [], { refresh: [ 'state' ], refreshDelay: 1000 })) .then(checkResult); } `
> ...

... and this is work for me
