### ISSUE TITLE
Roborocks doesn't react

### ISSUE THREAD

**Issue by iGodPhil** [nicoh88/homebridge-xiaomi-roborock-vacuum#58]
Hey I have some problems with this plugin. 

Sometimes the roborocks doesn't react in Homekit. They are connected and I can start, stop, pause etc into the mi home app every time. The log of homebridge UI seems to be right.

> [2019-7-13 6:31:37 PM] [Roborock Oben] ACT setSpeed | roborock.vacuum.s5 | FanSpeed set to 100 over miIO for "Max".
> [2019-7-13 6:31:37 PM] [Roborock Oben] ACT setCleaning | roborock.vacuum.s5 | Start cleaning, not charging.
>       pi : TTY=pts/2 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
> pam_unix(sudo:session): session opened for user root by (uid=0)

Once it works, sometimes it doesn't work. 
What can be the problem?

**Comment by backfisch88** [comment]
Unplug the Server and restart. :)

**Comment by iGodPhil** [comment]
Do you mean homebridge or into the mi home app?

Because i don't want to restart homebridge every day.

**Comment by iGodPhil** [comment]
Ah ok, sehe grade, dass du auch deutsch sprichst. Würde die ganze Sache vereinfachen. 

Jedenfalls reagieren die Robos ab und zu nicht wenn ich sie über Homekit starten möchte. Macht natürlich wenig Sinn, denn so können die ganzen Automationen über Homekit nicht starten.

**Comment by backfisch88** [comment]
Ich hatte das Problem, dass die automation nicht geklappt hat. Hab dann einfach den pi vom Strom und wieder dran. Dann ging es. 
Und wenn ich den neu starte überprüfe ich das. Und zur Not noch ein restart. Keine Ahnung woran das liegt 😂

**Comment by afharo** [comment]
It looks like it could be related to: https://github.com/aholstenson/miio/issues/196
It just occurred to me when manually triggering a clean up (today my automation didn't work).

I didn't actually need to restart the process, but had to retry 4 times to get it to work... :s

I think the last line in this excerpt from the logs should give us some hints...
```
0|Homebridge  | 2019-07-14T15:04:33.250Z miio:packet -> <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
0|Homebridge  | [7/14/2019, 3:04:33 PM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | Socket [object Object] is still on. Reusing it.
0|Homebridge  | 2019-07-14T15:04:33.257Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5d 2b 44 81 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
0|Homebridge  | 2019-07-14T15:04:33.258Z miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 c5 54 54 5d 2b 44 81 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
0|Homebridge  | 2019-07-14T15:04:33.259Z thing:miio:96818260 <- Handshake reply: <Buffer ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff>
```
Looking for that entry in the logs it rarely shows up (I could find 5 days difference between those entries). Maybe it has something related to it? MIIO failing to refresh the handshake and getting stuck there for a while?

**Comment by backfisch88** [comment]
For me it works to restart the raspberry

**Comment by iGodPhil** [comment]
So after i have reinstalled the plugin manually about the terminal i have no problems anymore. It was important to install the plugin as superuser. Without superuser i got some errors. But its documented in the wiki. I dont know what goes wrong if you want to install the plugin about homebridge ui.

Now i don't have to restart homebridge or the robos doesn't react.
