### ISSUE TITLE
Can't install on Hoobs 

### ISSUE THREAD

**Issue by mszf** [nicoh88/homebridge-xiaomi-roborock-vacuum#60]
Can't install on Hoobs because of missing miio.git ? any clue?

`hoobs@hoobs:/var/lib/homebridge $ sudo npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/nicoh88/miio.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by nicoh88** [comment]
Try:

```
sudo su -
npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
```

`sudo su -` is important

**Comment by mszf** [comment]
I have tried with sudo su - too without any success, same errors. Wonder if this could be related just to Hoobs

**Comment by mszf** [comment]
Ok, I found a solution. You need first install git "apt-get install git" to make this work on Hoobs then you don't even need sudo su -
Thanks anyway.

**Comment by racemase76** [comment]
Thanks, you've saved my day! Had exactly the same issue, installing git first resolved it.
