### ISSUE TITLE
ERR Constructor - S5

### ISSUE THREAD

**Issue by sahnebar** [nicoh88/homebridge-xiaomi-roborock-vacuum#61]
Guten Morgen, 

ich möchte mich als aller erstes für die geile Arbeit von dir bedanken! Sau cool dass du hier so ein nettes Plugin geschrieben hast. 👍 

Allerdings haut bei mir irgendwas mit der Verbindung nicht ganz hin, hast du eine Idee was hier falsch läuft? Für mein Verständnis habe ich soweit alles richtig konfiguriert. 

Anbei der Link zu pasted mit allen Infos: 
http://pasted.co/3b424217

Vielen Dank.

**Comment by nicoh88** [comment]
Falscher Token? Falsche IP? Kein Internet?

Bitte mit mirobo prüfen:
https://github.com/rytilahti/python-miio

---

`mirobo --ip 192.168.X.XXX --token ABCDEFG`
`mirobo info --ip 192.168.X.XXX --token ABCDEFG`

---

Gruß

**Comment by sahnebar** [comment]
Hey, vielen dank für die schnelle antwort, aber das läuft alles so wie es soll... 

root@debian:/home/peter# mirobo --ip 192.168.2.47 --token 7930766152696d4b534a58XXXXXXXXXX info
roborock.vacuum.s5 v3.3.9_001886 (40:31:3C:AD:D2:30) @ 192.168.2.47 - token: 7930766152696d4b534a585237757849
root@debian:/home/peter# mirobo --ip 192.168.2.47 --token 7930766152696d4b534a58XXXXXXXXXX
State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 0:00:00
Cleaned area: 0.0 m²

**Comment by sahnebar** [comment]
> Falscher Token? Falsche IP? Kein Internet?
> 
> Bitte mit mirobo prüfen:
> https://github.com/rytilahti/python-miio
> 
> ```
> mirobo --ip 192.168.X.XXX --token ABCDEFG`
> State: Charging
> Battery: 100 %
> Fanspeed: 60 %
> Cleaning since: 0:39:55
> Cleaned area: 33.595 m²
> ```
> 
> ```
> mirobo --ip 192.168.X.XXX --token ABCDEFG info
> rockrobo.vacuum.v1 v3.3.9_003600 (78:11:DC:7D:XX:YY) @ 192.168.X.XXX - token: ABCDEFG
> ```
> 
> Gruß

**Comment by nicoh88** [comment]
❓

**Comment by sahnebar** [comment]
ahh ich wollte ned zu machen, hab mich nur verklickt :P

**Comment by sahnebar** [comment]
Wie du siehst gehts ja mit dem Token und der IP, habs jetzt auch extra beim Output nicht weg ge "XXed" :P

**Comment by nicoh88** [comment]
Hmm, ja, sehe ich. Kann mir das Problem aktuell nicht erklären.

Noch eine Prüfung:
`grep -i Vacuum /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/models.js`

**Comment by sahnebar** [comment]
```
hb@homebridge:/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum$ grep -i Vacuum /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/models.js
const Vacuum = require('./devices/vacuum');
        'rockrobo.vacuum.v1': Vacuum,
        'roborock.vacuum.s5': Vacuum,
        'roborock.vacuum.c1': Vacuum,
        'roborock.vacuum.s6': Vacuum,
        'roborock.vacuum.t6': Vacuum,
```

**Comment by nicoh88** [comment]
Gibt es nicht. Sollte alles funktionieren. Sieht alles gut aus!

Sag mal, kannst du die `mirobo` Befehle auch auf dem homebridge System ausführen? Das sind doch zwei unterschiedliche Systeme (debian, homebridge) oder?

**Comment by sahnebar** [comment]
öhm, die mirobo Befehle kann ich nur auf dem debian ausführen, wollte mein homebridge nicht unnötig vollmüllen. Netzwerkmäßig sind die alle im 192.168.x.x netz ohne irgendwas dazwischen. 

Das homebridge System ist ein Ubuntu.
```
hb@homebridge:/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum$ uname -a
Linux homebridge 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

hb@homebridge:/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by nicoh88** [comment]
Keine Ahnung. Ich finde es eigenartig. Sollte auch auf dem Ubuntu laufen. Kann eigentlich nur am Netzwerk liegen. Mich würde schon interessieren ob die `mirobo` Befehle auf dem Ubuntu (Hostname: homebridge) funktionieren würden.

**Comment by sahnebar** [comment]
Alles klar kein Thema, genau aus dem Grund hab ich dir geschrieben weil es für mich auch keinen Sinn macht :) 
Ich werde das mal installieren, dann sag ich dir gleich bescheid.

**Comment by sahnebar** [comment]
uffz... also ich hab schlechte Nachrichten, es geht auch mit den Befehlen auf dem homebridge system. 
Die Frage is nur was kann ich jetzt noch machen? Alles nochmal neu einrichten? 
```
root@homebridge:~# mirobo --ip 192.168.2.47 --token 7930766152696d4b534a585237757849
State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 0:00:00
Cleaned area: 0.0 m²
root@homebridge:~# mirobo --ip 192.168.2.47 --token 7930766152696d4b534a585237757849 info
roborock.vacuum.s5 v3.3.9_001886 (40:31:3C:AD:D2:30) @ 192.168.2.47 - token: 7930766152696d4b534a585237757849
```

**Comment by nicoh88** [comment]
Unfassbar. Ich kann es mir nicht erklären.

Habe jetzt auch mal das Firmware-Update `3.3.9_001886` installiert, bei mir funktioniert es auch mit der 1886. 👎

**Comment by backfisch88** [comment]
Auch mit dem s6 (neuste Version 3.4.5_0524) gehts einwandfrei

**Comment by backfisch88** [comment]
Verschiedene subnetze?! 
Roboter reset und neu ins wlan?

**Comment by sahnebar** [comment]
Verschiedene Subnetzte habe ich zu hause nicht :P hab lediglich das 192.168.2.X. 

Den Reset des robos kann ich heute Abend mal testen obs dann besser wird. Sollte ich vielleicht alles nochmal neu auf nem anderen Ubuntu release installieren? 
--> Auf welchem Linux läuft das denn bei euch?

**Comment by nicoh88** [comment]
> --> Auf welchem Linux läuft das denn bei euch?

Bis vor einer Woche war es ein Raspbian 9 (Debian 9) auf einem RPi 3. Jetzt auf einem Debian 10 auf meinem Self-Made-NAS.

Der RPi 3 war mit 6 Homebridge-Instanzen, über 80 Geräten und einigen FakeGato-Historys mittlerweile etwas überfordert. ✋

**Comment by backfisch88** [comment]
6 Instanzen?! 😂 was machstn damit?

Hab auf 2 raspberrys, raspbian 9 laufen. Insgesamt fast 100 Geräte. + ne homematic + 15 Sensoren für Temperatur usw

**Comment by sahnebar** [comment]
> 
> 
> Verschiedene subnetze?!
> Roboter reset und neu ins wlan?

Den Robi werde ich am Wochenende mal neu ins WLAN bringen. Unter der Woche bin ich leider nicht zu hause. :) 
Aber Ich hab parallel schonmal das Ganze auf nem Debian installiert und bekomme dort die gleichen Fehler... >.< also irgendwas stimmt da einfach ned. Vorm Netzwerk her habe ich alles über das 192.168.2.X seht selbst: https://screenpresso.com/=GI9Se

**Comment by nicoh88** [comment]
> Den Robi werde ich am Wochenende mal neu ins WLAN bringen. Unter der Woche bin ich leider nicht zu hause. :)
> Aber Ich hab parallel schonmal das Ganze auf nem Debian installiert und bekomme dort die gleichen Fehler... >.< also irgendwas stimmt da einfach ned. Vorm Netzwerk her habe ich alles über das 192.168.2.X seht selbst: https://screenpresso.com/=GI9Se

Komisch, ich verstehe es nicht.

Du hast bei deinem Homebridge- bzw. Debian-System keine Ports blockiert (Zugangsprofile in der FRITZ!Box)? Hast du dem Roborock ein Zugangsprofil verpasst?

![Bildschirmfoto 2019-07-25 um 09 24 32](https://user-images.githubusercontent.com/264264/61854435-5c798d80-aebe-11e9-9bd7-cf384672ea67.jpg)

> 6 Instanzen?! 😂 was machstn damit?

Naja, habe die Erfahrung gemacht, dass manchmal Plugins einfach Quick'n'Dirty programmiert sind und nicht alle Fehlermeldung abgefangen werden. 
So ist es bei mir schon einige Male vorgekommen, dass ein Plugin, alle andere Plugins und Geräte einer Homebridge-Instanz mit in Abgrund gerissen hat und dann auf "**Keine Antwort**" standen. Daher splitte ich die Plugins immer in unterschiedliche Instanzen auf.

**Comment by Huelsi** [comment]
Hallo zusammen, ich habe den robo gestern auch in Betrieb genommen. Bin selber auch auf der 1886 und habe das identische Fehlerbild. Allerdings taucht der robo trotzdem in der Home App auf und ich kann ihn auch ganz normal steuern.

**Comment by sahnebar** [comment]
Guten Morgen, 
mensch hat echt lange gedauert, aber ich habs jetzt mehr oder weniger hinbekommen. :P

Die Fehler werden nach wie vor noch angezeigt, aber jetzt wird mir der Robo im AppleHomekit angezeigt. Dementsprechend ist er auch nutzbar, perfekt. :)

Ich hab überlegt ob es mit meinen Setup zu tun hat, dass immer wieder die Fehler kommen... Wollen wir hier noch ein bisschen weiter analysieren um das in den Griff zu bekommen? Falls ja musst du mir nur sagen was du alles brauchst dann bereite ich das auf und lass es dir zukommen. ;)

**Comment by nicoh88** [comment]
Kann das Problem leider nicht nachvollziehen. Daher mache ich hier zu.
