### ISSUE TITLE
Xiaowa Lite C10 not working good

### ISSUE THREAD

**Issue by bucikowyyy** [nicoh88/homebridge-xiaomi-roborock-vacuum#62]
I have two vacuum s55 working good but my new Xiaowa Lite C10 not nessesery.
Xiaowa Lite C10 can't start good. When i click button in home kit I have error:
"
ERR setPauseState | roborock.vacuum.c1 | Failed updating pause state false. Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:16:9)

ERR setCleaning | roborock.vacuum.c1 | Failed to set cleaning to false Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:16:9)

"
after that vacuum started but i can't stop him. this is very interesting because  I can pause him.

**Comment by nicoh88** [comment]
Sorry, unfortunately I can not do anything. I do not have a test device and, the developer of the Miio API is no longer active, I can not make major adjustments.
