### ISSUE TITLE
Named fanspeed modes gone for S50 (speedmodes_gen2)?

### ISSUE THREAD

**Issue by lexpostma** [nicoh88/homebridge-xiaomi-roborock-vacuum#63]
Hi,

I seem to remember that the first time I used this plugin the vacuum offered fanspeed steps with names when 3D touching the icon. However, now it's just a percentage slider.

I have a Roborock S50, so I should be seeing this on 3D Touch, right?

- Off (0%)
- Mopping (1-15%)
- Quiet (16-38%)
- Balanced (39-60%)
- Turbo (61-75%)
- Max Speed (76-100%)

Did I misremember? Or did I break something? Can you help me get it back? Or if I misremembered, can I help in adding the feature?

— Lex

**Comment by nicoh88** [comment]
Hi Lex,

you misremember.
This is with Apple HomeKit not possible.

Sorry
