### ISSUE TITLE
Xiaomi Vacuum 1S (not just 1, 1S) is not recognised

### ISSUE THREAD

**Issue by vmiraboronat** [nicoh88/homebridge-xiaomi-roborock-vacuum#64]
Hello,

It seems that the new Vacuum model 1S (an improvement from the 1st Gen) is not being recognised. I get the error
ERR getDocked | No vacuum cleaner is discovered yet
ERR getDevice | Is not a vacuum cleaner!

Adding manually the token to miio, the device shows this info:

miio inspect 192.168.1.156
 INFO  Attempting to inspect 192.168.1.156

Device ID: 260239815
Model info: roborock.vacuum.m1s
Address: 192.168.1.156
Token: 6d7a62614e6c5a6c4941366d4d47335a via stored token
Support: At least generic

Type info: miio
Capabilities:

Firmware version: 3.4.5_0848
Hardware version: Linux

It shows no capabilities which is not a good thing...
I guess that due to the newest model, it still has not been included in the miio database.

**Comment by nicoh88** [comment]
Hi @vmiraboronat,

i add the `roborock.vacuum.m1s`.
Unfortunately, I can not do more. Try it, maybe everything works. 🙏 

```
npm uninstall -g homebridge-xiaomi-roborock-vacuum
npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
```

**Comment by vmiraboronat** [comment]
Thanks for the update @nicoh88. It is working!!. It seems that the speed do not quite match, as it reports over 100%, but it does the job :-)

For a basic operation of the device, it is working perfectly for me.

Again, thanks!!!
