### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by PatrickSTM** [nicoh88/homebridge-xiaomi-roborock-vacuum#67]
Hello :)

There seems to be a problem.
I installed the Homebridge plugin, entered the token and the Ip address. After restarting the Homebridge the vacuum cleaner also appeared in the Home App, but it says "no answer". I have activated all options.

Following is in the config:

`"accessories": [
        {
            "name": "Dirty Harry",
            "ip": "192.168.178.52",
            "token": "c952a406c5340c61b669ff7b0b1931ce",
            "pause": true,
            "dock": true,
            "accessory": "XiaomiRoborockVacuum"
        }
    ]`

If you need some more information, you can ask me.
Many greetings from Hannover :)

**Comment by PatrickSTM** [comment]
![cleaner](https://user-images.githubusercontent.com/13473121/65132433-3aeddb80-da01-11e9-802f-e8f4efb775cb.PNG)
Here the error output. It says the device is no vaccum cleaner. But it is!
It is the xiaowa e series.

**Comment by PatrickSTM** [comment]
MiioDevice Object:

MiioDevice {
  model=roborock.vacuum.e2,
  types=miio,
  capabilities=
}

**Comment by PatrickSTM** [comment]
I entered into the if statement which checks if the device is a vaccum cleaner. This is the result.
I don't know why its not working...

`[9/18/2019, 11:19:41 AM] [Dirty Harry] Initializing XiaomiRoborockVacuum accessory...
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | Connected to: 192.168.178.52
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | Model: roborock.vacuum.e2
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | State: undefined
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | FanSpeed: undefined
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | BatteryLevel: undefined
[9/18/2019, 11:19:41 AM] [Dirty Harry] INF getSerialNumber | roborock.vacuum.e2 | Serial Number is undefined
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | Serialnumber: undefined
[9/18/2019, 11:19:41 AM] [Dirty Harry] INF getFirmware | roborock.vacuum.e2 | Firmwareversion is 1.3.0_0686
[9/18/2019, 11:19:41 AM] [Dirty Harry] STA getDevice | Firmwareversion: 1.3.0_0686
[9/18/2019, 11:19:41 AM] [Dirty Harry] ERR getState | this.device.state | TypeError: this.device.state is not a function`

**Comment by thechris1992** [comment]
new fw?

**Comment by PatrickSTM** [comment]
Firmware is updated. Or what do you mean?

**Comment by afharo** [comment]
Hey! I can see your model is `roborock.vacuum.e2`. It is not listed yet as a valid model. Similarly, it might not be updated in the miio package. @nicoh88 we might need to update both

**Comment by nicoh88** [comment]
Done. ✅ Version 0.6.4 published.

FanSpeed is `speedmodes_gen3` for `roborock.vacuum.e2`. No idea if right. 👎 

```
sudo su -
npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm
```

**Comment by afharo** [comment]
Thank you @nicoh88! I can see you also updated the miio module accordingly. @PatrickSTM, when testing, please, make sure the miio module is also updated to version `"0.15.8-nicoh88"`

**Comment by monteroman** [comment]
Hey there!   I have a RoboRock S5 with firmware 3.3.9_001886 that I'm  trying to get to work, but i'm also seeing the errors:

INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device

I have a dhcp reservation for the IP of the vac and I know that's working properly.  I have the Miio package installed.    Any thoughts as to where I might be going wrong?

Thanks!

**Comment by afharo** [comment]
Hi @monteroman, I have the exact same model and firmware and it's working just fine for me.

Q: Do you see the error `'ERR getDevice | Is not a vacuum cleaner!'`? If so, I'm afraid either the token or the IP are wrong.

**Comment by monteroman** [comment]
I did finally get it running 2 nights ago.  Yup, token was wrong.

**Comment by afharo** [comment]
Great to hear that! I'll close this issue then if you don't mind.

**Comment by monteroman** [comment]
I don’t mind at all.  Thank you for the follow up.
