### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not complete call to device

### ISSUE THREAD

**Issue by Bankaifan** [nicoh88/homebridge-xiaomi-roborock-vacuum#7]
Ich erhalte folgende Meldung im Log
homebridge-miio musste ich deinstallieren, da es sich wohl nicht mit node 9.10.0 verträgt

Ggf. hängt das Problem damit zusammen, dass man jetzt auch beim Vacuum Zonen definieren kann.

[2018-4-4 10:26:32] [Staubsauger] ACTION | Start cleaning.
[2018-4-4 10:26:33] [Staubsauger] MONITOR | ChargingState has changed, is now false
[2018-4-4 10:26:33] [Staubsauger] INFO | Charging was canceled.
[2018-4-4 10:26:33] [Staubsauger] MONITOR | CleaningState has changed, is now true
[2018-4-4 10:26:33] [Staubsauger] INFO | Cleaning was started.
(node:31863) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:13:9)
    at <anonymous>
(node:31863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

pi@raspberrypi:~ $ list-versions 
###############################################
Plugin Versionen:
/usr/local/lib
├── homebridge@0.4.38
├── homebridge-broadband@1.0.1
├── homebridge-config-ui-x@3.4.0
├── homebridge-dacp@0.9.1
├── homebridge-fritz@0.6.0
├── homebridge-people@0.6.2
├── homebridge-philipstv-x@0.5.0
├── homebridge-raspberrypi-temperature@0.0.6
├── homebridge-wol@3.2.1
├── homebridge-xiaomi-roborock-vacuum@0.2.1
├── n@2.1.8
└── npm@5.8.0

NPM-Version
5.8.0
Node-Version
v9.10.0
Roboter-Firmware
3.3.9_003194

**Comment by nicoh88** [comment]
Bug in miio with S50/S51 (Gen2) oder v1 (Gen2) mit neuerer Firmware: https://github.com/aholstenson/miio/issues/130

**Comment by nicoh88** [comment]
@Bankaifan wenn du auf Version 0.2.2 aktualisierst, sollte das Problem behoben sein. 😉 

Bitte um eine kurze Info.

**Comment by Bankaifan** [comment]
Bis jetzt keine Meldung mehr. Die kam aber in den 8 Tage auch nur noch ein mal. Ich beobachte mal weiter.
