### ISSUE TITLE
New update wont install

### ISSUE THREAD

**Issue by JonoHaysom** [nicoh88/homebridge-xiaomi-roborock-vacuum#71]
CMD: npm --no-update-notifier install --unsafe-perm homebridge-xiaomi-roborock-vacuum@latest

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/nicoh88/miio.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

npm ERR! A complete log of this run can be found in:

**Comment by afharo** [comment]
It looks like a Mac OS issue. Have you updated XCode?
https://stackoverflow.com/questions/32896524/invalid-active-developer-path-error-after-upgrading-to-el-capitan

**Comment by JonoHaysom** [comment]
It looks like apple didn't include the new command line tools in the Catalina Xcode 11 update. manual intervention has indeed fixed this. thanks @afharo
