### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by costispavlou** [nicoh88/homebridge-xiaomi-roborock-vacuum#74]
I added your plugin in hoobs service and was so glad that it worked as soon as I input the token. 
Since the first check the vacuum (roborock S5) is not responding whatever I do. 
I reset wifi, I reinstalled, uninstalled, installed.. 
What am I doing wrong?

**Comment by afharo** [comment]
Hi @costispavlou ,
What do you mean with “it worked as soon as I input the token” and then “is not responding”?
Can you please elaborate? If you could provide some logs as well, it would be amazing!

**Comment by costispavlou** [comment]
Hi thanks for the quick reply. I mean it only worked once. Now it shows on home.app as not responding

**Comment by costispavlou** [comment]
![image](https://user-images.githubusercontent.com/57916603/69082481-da067200-0a48-11ea-8ebb-3f76728ecb8c.jpg)

**Comment by costispavlou** [comment]
![D3FC43BC-4529-420B-9310-120E00401BD6](https://user-images.githubusercontent.com/57916603/69097725-d0d4cf80-0a5f-11ea-919b-7675ff4ae792.png)

**Comment by afharo** [comment]
According to the logs it looks like it cannot connect to your robot. It usually is due to the IP or the token being wrong. Can you make sure both are correct?
We’ve seen in the past, as well, some routers have different subnetworks between the 2.4GHz and the 5GHz (my BT router was one of them) despite being named the same. When that happens, it’s not possible to find the device.

**Comment by costispavlou** [comment]
If token can somehow change then yeah, i need to find it again but i really doubt thats the case. Also the wifi is 2,4ghz.
I did change the roborocks’ name and was experimenting with more plugins but since it worked the first few times, i’m really struggling to find what went wrong..

**Comment by afharo** [comment]
The token should be static overtime unless you reset/reconfigure the robot through the app. In the past, when I reconfigured the WiFi connection in my robot, I had to retrieve the token again. Maybe that will help?

**Comment by costispavlou** [comment]
Yeah maybe that’s it. I’ll recover the token again using a new backup. There’s no other easier way right?

I’ll let you know tonight

**Comment by afharo** [comment]
🤞

**Comment by costispavlou** [comment]
Yup. Token is different. Thanks so much. 
Hope this helps others too!

**Comment by afharo** [comment]
Awesome! Thank you for confirming. Closing the issue then, if you don’t mind.
