### ISSUE TITLE
Can't update to newest version on osx

### ISSUE THREAD

**Issue by kimme1024** [nicoh88/homebridge-xiaomi-roborock-vacuum#77]
Hi, 

I just tried to update to the newest version without success.

Output:
Mac-mini-van-Kim:~ XBMC$ sudo npm install -g homebridge-xiaomi-roborock-vacuum --unsafe-perm
Password:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /Users/XBMC/.npm/_cacache/tmp/git-clone-e676b06c
npm ERR! /Users/XBMC/.npm/_cacache/tmp/git-clone-e676b06c/.git: Permission denied
npm ERR! 

I found in another issue that this might be caused by xcode not being updated so I did that to be sure but the issue remains.

Any ideas?

Thanks in advance!

**Comment by afharo** [comment]
Can you follow the steps detailed in https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/71

**Comment by kimme1024** [comment]
> Can you follow the steps detailed in #71

Is I mentioned in my initial post I already checked #71 without success.
I'm running the latest version of xcode and I'm not running Catalina so that issue doesn't apply to this case.

**Comment by kimme1024** [comment]
Today I took some time to check this out again.
I updated xcode, checked the cl-tools but the error remains.

I'm on macOS 10.13.6 with xcode 10.1 installed.

**Comment by afharo** [comment]
I think the key point is in here:
`npm ERR! /Users/XBMC/.npm/_cacache/tmp/git-clone-e676b06c/.git: Permission denied`. 

Do you have permissions to write in that folder?

**Comment by kimme1024** [comment]
Hi afharo, thanks for the reply.

I checked and the folder doesn't exist.
Just to try I granted full access to the last existing folder (tmp) but the error remains the same.
Any ideas on how to solve this?

Thanks in advance!

**Comment by kimme1024** [comment]
I updated npm and this fixed the issue for me
