### ISSUE TITLE
S5 max - fan speed and mopping modes

### ISSUE THREAD

**Issue by MaurizioB84** [nicoh88/homebridge-xiaomi-roborock-vacuum#79]
Hello,

I configure correctly (I think) the roborock s5 max but the plugin not recognised it. 

this is the log:
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] ERR getBatteryLow | No vacuum cleaner is discovered yet.
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] ERR getDevice | Is not a vacuum cleaner!

the config is the following:

        {
            "name": "Roborock",
            "ip": "192.168.2.124",
            "token": "xxxx767358306974534263584747xxxx",
            "pause": true,
            "dock": true,
            "accessory": "XiaomiRoborockVacuum"
        }

**Comment by MaurizioB84** [comment]
log detailed: 
```
homebridgeTLS  | [12/14/2019, 10:05:15 PM] [Roborock] ERR getDevice | Is not a vacuum cleaner!
homebridgeTLS  | [12/14/2019, 10:05:15 PM] [Roborock] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
homebridgeTLS  |     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:485:32)
homebridgeTLS  |     at XiaomiRoborockVacuum.getCleaning (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:493:31)
homebridgeTLS  | 
homebridgeTLS  | [12/14/2019, 10:05:15 PM] [Roborock] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
homebridgeTLS  |     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:485:32)
homebridgeTLS  |     at XiaomiRoborockVacuum.getCleaning (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:493:31)
homebridgeTLS  | 
```

**Comment by Itzamna44** [comment]
Hello.
I have S5 Max too. 
Please add this to the list of supported devices.
Thank You.

**Comment by Reddyzinho** [comment]
Have this one also.... :/ Anybody knows how to put this working?

**Comment by infernalK** [comment]
Hello I have the same problem

**Comment by afharo** [comment]
Hi! 
Sorry for being dormant in my response.

From the extract of the logs, if you could find the `debug` message right after the error message `'ERR getDevice | Is not a vacuum cleaner!'`, we might be capable of finding out what's the model and hopefully add it to the list of known devices.

We'll work on the next release to include the model name in the error level so there is no need to run it in debug mode.

**Comment by infernalK** [comment]
In the database used to extract the token the field ZMODEL is robotics.vacuum.s5e hope this will help.

**Comment by nicoh88** [comment]
`robotics.vacuum.s5e` added

please test the github master version:

```
sudo su -
npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master --unsafe-perm
```

thanks for feedback 🥇

**Comment by infernalK** [comment]
Thanks
I think automatic correction change what I was trying to write. It’s not robotics but roborock. Sorry for the mistake

**Comment by nicoh88** [comment]
Ok. Typofix.
Test it again.

**Comment by infernalK** [comment]
Thanks a lot it works

**Comment by infernalK** [comment]
The battery level does'nt show in Home however I get the value in the log.
I'm not sure but may be there is 2 differents settings for fanspeed and mopping like in the app

[2020-1-13 16:11:18] [Aspirateur] STA getDevice | Connected to: 192.168.1.81
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | Model: roborock.vacuum.s5e
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | State: charging
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | FanSpeed: 102
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | BatteryLevel: 100
[2020-1-13 16:11:18] [Aspirateur] INF getSerialNumber | roborock.vacuum.s5e | Serial Number is R0503S94603695
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | Serialnumber: R0503S94603695
[2020-1-13 16:11:18] [Aspirateur] INF getFirmware | roborock.vacuum.s5e | Firmwareversion is 3.5.4_0540
[2020-1-13 16:11:18] [Aspirateur] STA getDevice | Firmwareversion: 3.5.4_0540
[2020-1-13 16:11:18] [Aspirateur] INF changedCleaning | roborock.vacuum.s5e | Cleaning is OFF.
[2020-1-13 16:11:18] [Aspirateur] MON changedCharging | roborock.vacuum.s5e | ChargingState is now true
[2020-1-13 16:11:18] [Aspirateur] INF changedCharging | roborock.vacuum.s5e | Charging is active
[2020-1-13 16:11:18] [Aspirateur] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
[2020-1-13 16:11:18] [Aspirateur] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 102%
[2020-1-13 16:11:18] [Aspirateur] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 102%, this speed is not supported
[2020-1-13 16:11:18] [Aspirateur] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning

**Comment by nicoh88** [comment]
Seems `speedmodes_gen3`.

Please confirm, over homebridge log:

```
...
Quiet = 101
Balanced = 102
Turbo = 103
Max = 104
...
```

**Comment by infernalK** [comment]
Seems to be something like that but in the app there a setting for water level : no / low / medium / high

here is my log

root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | Connected to: 192.168.1.81
bash: Connected : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | Model: roborock.vacuum.s5e
bash: Model: : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | State: charging
bash: State: : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | FanSpeed: 102
bash: FanSpeed: : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | BatteryLevel: 100
bash: BatteryLevel: : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF getSerialNumber | roborock.vacuum.s5e | Serial Number is R0503S94603695
bash: roborock.vacuum.s5e : commande introuvable
bash: Serial : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | Serialnumber: R0503S94603695
bash: [2020-1-13 : commande introuvable
bash: Serialnumber: : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF getFirmware | roborock.vacuum.s5e | Firmwareversion is 3.5.4_0540
bash: roborock.vacuum.s5e : commande introuvable
bash: Firmwareversion : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] STA getDevice | Firmwareversion: 3.5.4_0540
bash: Firmwareversion: : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF changedCleaning | roborock.vacuum.s5e | Cleaning is OFF.
bash: roborock.vacuum.s5e : commande introuvable
bash: [2020-1-13 : commande introuvable
bash: Cleaning : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] MON changedCharging | roborock.vacuum.s5e | ChargingState is now true
bash: roborock.vacuum.s5e : commande introuvable
bash: ChargingState : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF changedCharging | roborock.vacuum.s5e | Charging is active
bash: Charging : commande introuvable
bash: [2020-1-13 : commande introuvable
bash: roborock.vacuum.s5e : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
bash: roborock.vacuum.s5e : commande introuvable
bash: Robot : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 102%
bash: roborock.vacuum.s5e : commande introuvable
bash: [2020-1-13 : commande introuvable
bash: FanSpeed : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 102%, this speed is not supported
bash: roborock.vacuum.s5e : commande introuvable
bash: Speed : commande introuvable
bash: [2020-1-13 : commande introuvable
root@raspberrypi:/home/pi# [2020-1-13 16:11:18] [Aspirateur] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning

**Comment by nicoh88** [comment]
Sorry. Misunderstanding.

Please take a look at the Homebridge log, then, gradually, set all modes and note the FanSpeed which is then displayed in the log.

Example:
```
...
Quiet = 101
Balanced = 102
Turbo = 103
Max = 104
Mop = ?
...
```

**Comment by infernalK** [comment]
Sorry my bad. I will try do that this evening.

**Comment by infernalK** [comment]
hello,
I'm back with the values 

Soft = 105
Quiet = 101
Balanced = 102
Turbo = 103
Max = 104
Mop = 15

I have still have a question about how de set the water level for mopping. I tried all the settings in the app but always have 

[2020-1-15 13:47:20] [Aspirateur] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 105%
[2020-1-15 13:47:20] [Aspirateur] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 105% (Mop), for HomeKit 15%

**Comment by infernalK** [comment]
Another point : The battery level seems to read but in the accessories it's marked not supported and it doesn't appear in HomeKit
[2020-1-15 13:37:18] [Aspirateur] INF getBattery | roborock.vacuum.s5e | Batterylevel is 65%

**Comment by afharo** [comment]
I believe the "official" Home app does not show many of the details provided by the devices. You can use the app `Eve` to see more details:
![IMG_1300](https://user-images.githubusercontent.com/5469006/72655117-d9c41d80-398a-11ea-9cd8-2226142f8047.PNG)

Regarding the errors, we are currently only logging them. I'm not entirely sure if `homebridge` provides a way to push error status notifications to HomeKit. We can reply back to actions with errors though (although I'm not sure how it's handled in HomeKit).

**Comment by infernalK** [comment]
Thanks for the answer. I’m a beginner with homebrige so I don’t really know how it works. I have all the informations in the Xiaomi mihome app, but I was thinking I can make my own alert for washing accessories.

**Comment by afharo** [comment]
You still have the Care indicators (in the eve app). You can create rules to be triggered when the care indicators are >= a certain value. 
NB: 100% is need some care. 0% is all good :)

**Comment by MaurizioB84** [comment]
> You still have the Care indicators (in the eve app). You can create rules to be triggered when the care indicators are >= a certain value. Even when created in the app eve. It is later understood and ran in the Home app
> NB: 100% is need some care. 0% is all good :)
Which type of rules can you suggest?

**Comment by infernalK** [comment]
For example filtre need to be washed every 15 days. As we have hours of use I was thinking of calculating the 15 days in hour and having an indicator saying need to wash the filter for example.

**Comment by afharo** [comment]
You can see [this is the logic](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/8e6caf45fab75ef3d0b8cec248e1c0439b811c9f/index.js#L653-L661) to calculate the "Care indicator filter": `(currentValue / 150h) * 100`.

You can set an automation in the Eve app where the trigger is what you prefer (when the vacuum cleaner goes off, when it gets to charge, every weekend, ...) and the condition is the Care indicator filter is >= 100% (or 80% or any other value you might prefer), then trigger some event you may want to notify you (personally, I'm using the plugin `homebridge-automation-switches` to have programmable switches to trigger based on automations).

A good example to show you the use of the plugin I just mentioned: 
- I have an automation where, every time the vacuum cleaner starts, it sets a switch on (I called it "Cleaning started").
- Every day at 7 am I reset that switch
- When the last person leaves the flat, I check if that switch is still OFF (it hasn't cleaned up yet today) and then it starts the vacuum cleaner. If it's ON, it means we left the flat, then we came back and left again (I don't want the cleaning to start again on the same day).

You can set one of the switches ON when the care indicator is over a threshold and you'll see that in your Home app. If you want notifications, I believe you can use locks or sensors instead :)

If it becomes a common request, we can implement in this plugin (optional) sensors that will fire off when the Care indicators are over 100% so no other plugin is required. 
It should be pretty straightforward to implement.
@nicoh88 what do you think?

**Comment by infernalK** [comment]
Thank you for all the information. If I understand I can pair my robot with the eve app but will it change the token? I will soon have a look on how to create plugin I’m a developer in Delphi language and I’m very curious about what I can do with my rpi and phone 😉

**Comment by MaurizioB84** [comment]
guys, I tried it and it's works, not perfectely because I cannot set max mode for vacuum and I cannot control the water quantity for now...

But it's works, I can help you to test the previous functionality? :)

**Comment by afharo** [comment]
> If I understand I can pair my robot with the eve app but will it change the token?

No need. The Eve app reads the info from the Home app. But it simply shows more details than the "official" one :) Think of it as the "advanced options of the Home app. :)

**Comment by afharo** [comment]
@MaurizioB84 thank you for confirming!

> I cannot set max mode for vacuum

Hmm, @nicoh88 I think we need to create a new mapping of levels for this model then, based on this comment: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/79#issuecomment-574650158

> I cannot control the water quantity for now...

I didn't know you could control that. Can explain more, please?

**Comment by infernalK** [comment]
Ok I’ll try the eve app.
Here is a picture of mop settings sorry it’s in French you have : none - low - medium - high
![96103B3C-1CBB-4B33-A02F-CCEE6BA78411](https://user-images.githubusercontent.com/59821935/72665421-9f00ca80-3a08-11ea-99f5-c73fd22e35f3.png)

**Comment by afharo** [comment]
Oh! Cool!

> sorry it’s in French

Haha! That's OK. I learned a bit of French back in school.
I'm wondering how the robot might report the water level through its API... Maybe running `homebridge` in debug mode (setting the environment var `DEBUG=*` or `DEBUG=miio*` (to be catch only the debug messages from the `miio` library) before the command gives us some extra insights about the data returned when requesting for the status of the robot.
Mine (the S5 model) does not have those options.

**Comment by infernalK** [comment]
I’ll try the debug mode and send you what I find may be I can do that on monday.

**Comment by infernalK** [comment]
Hello,
I tried to change modes via the robot app and here is what I get. may be you will find something.

janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.344Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":254}
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.344Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 94 9f fb 78 fd 2f bb 3f d4 bb 8e 03 16 ff ee 8d e3 3a>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.345Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":255}
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.346Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 94 9f b9 3f 29 5b 9d ee 2f da 33 2b 79 94 79 11 ed 9c>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.355Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 a0 e6 14 d9 5f 73 99 9e 46 72 b1 1d 4e 39 d4 85 9e>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.356Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 a0 e6 14 d9 5f 73 99 9e 46 72 b1 1d 4e 39 d4 85 9e>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.358Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1574,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":254}`
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.359Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 a0 5e d7 c7 bd 43 5e 55 0f a0 b9 28 0d 73 b4 4c 2e>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.359Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 a0 5e d7 c7 bd 43 5e 55 0f a0 b9 28 0d 73 b4 4c 2e>
janv. 20 12:53:04 raspberrypi homebridge[2026]: 2020-01-20T11:53:04.361Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":255}`
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.344Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":256}
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.348Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 94 bd de 9e a3 a7 88 71 7b 31 e8 0d d4 69 6b df b5 d7>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.348Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":257}
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.349Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 94 bd dd be 50 5e b7 bd 51 c9 43 3b dc 88 85 2e 24 72>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.357Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 be c5 ab bd b9 c1 36 43 21 ff b7 53 b5 02 26 9c fa>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.357Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 be c5 ab bd b9 c1 36 43 21 ff b7 53 b5 02 26 9c fa>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.358Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1590,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":256}`
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.359Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 be 90 36 cb cd 83 28 a1 48 42 22 29 35 f2 df 82 7f>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.360Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 be 90 36 cb cd 83 28 a1 48 42 22 29 35 f2 df 82 7f>
janv. 20 12:53:34 raspberrypi homebridge[2026]: 2020-01-20T11:53:34.361Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":257}`
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.345Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":258}
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.350Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 94 db e4 b4 70 2b 41 57 17 3a 61 23 73 2e e9 87 5f 1d>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.351Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":259}
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.351Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 94 db cf 4c 3a 14 b1 83 68 12 b3 55 dc 79 4f e7 af 73>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.365Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 dc 17 33 88 38 bf 1e 1c 7d 80 1b b4 d9 e2 72 b7 e1>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.365Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 dc 17 33 88 38 bf 1e 1c 7d 80 1b b4 d9 e2 72 b7 e1>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.366Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1606,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":258}`
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.368Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 dc 03 96 ff e5 63 22 72 49 59 11 0f 7f 9b 04 77 ee>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.368Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 dc 03 96 ff e5 63 22 72 49 59 11 0f 7f 9b 04 77 ee>
janv. 20 12:54:04 raspberrypi homebridge[2026]: 2020-01-20T11:54:04.369Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":259}`
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.345Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":260}
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.346Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 94 f9 b3 fb d9 ae 48 33 1d 8d d8 b0 43 7f 2d 0f 03 df>
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.346Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":261}
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.347Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 94 f9 e7 44 84 e2 a9 de a2 52 b1 4a b6 cb cb 07 5a fb>
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.359Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 fa 53 81 4e df 69 93 ba 00 82 9c 5b 40 cc 6a 54 ab>
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.360Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 94 fa 53 81 4e df 69 93 ba 00 82 9c 5b 40 cc 6a 54 ab>
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.361Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1622,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":200,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":260}`
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.362Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 94 fa e6 73 68 b3 0f 09 f5 3b 20 70 96 2d 78 0e a1 b6>
janv. 20 12:54:34 raspberrypi homebridge[2026]: 2020-01-20T11:54:34.363Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":261}`
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.346Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":262}
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.347Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 95 17 a8 98 a3 4c c6 f6 85 3c 45 ad 3f 24 d5 a1 ad 79>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.348Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":263}
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.348Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 95 17 81 8c b2 4c dd 9b 4b c6 6e cf cc be 08 59 ea 97>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.360Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 95 18 29 af 70 c0 17 c1 12 45 72 ca dd ab 43 2b 06 da>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.360Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 95 18 29 af 70 c0 17 c1 12 45 72 ca dd ab 43 2b 06 da>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.362Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1638,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":201,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":262}`
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.363Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 95 18 3d 47 b3 5d 06 28 1f 25 8c f1 98 6e e0 25 e1 99>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.364Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 95 18 3d 47 b3 5d 06 28 1f 25 8c f1 98 6e e0 25 e1 99>
janv. 20 12:55:04 raspberrypi homebridge[2026]: 2020-01-20T11:55:04.365Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":263}`
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.346Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":264}
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.347Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 25 95 35 14 47 25 79 fe d5 d9 a6 92 d5 43 66 49 54 c1 8e>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.347Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":265}
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.348Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 25 95 35 97 3a bc 56 bd d3 14 15 1f 44 cd 4a 9a ae 5f 79>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.356Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 95 36 1d b7 06 46 96 0e 8b e5 55 f7 c1 03 4b 66 37 79>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.357Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 25 95 36 1d b7 06 46 96 0e 8b e5 55 f7 c1 03 4b 66 37 79>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.358Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1654,"state":8,"battery":100,"clean_time":1589,"clean_area":25655000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":103,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":201,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":264}`
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.359Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 95 36 6b b0 22 ac 8a 4a 48 9a 5c 9d 2b b9 70 40 d3 8a>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.360Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 25 95 36 6b b0 22 ac 8a 4a 48 9a 5c 9d 2b b9 70 40 d3 8a>
janv. 20 12:55:34 raspberrypi homebridge[2026]: 2020-01-20T11:55:34.361Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":37735,"side_brush_work_time":37735,"filter_work_time":37735,"filter_element_work_time":35774,"sensor_dirty_time":37735}],"id":265}`

**Comment by infernalK** [comment]
What I found is that the parameter "water_box_mode" change when I set the different mopping modes like this :
no = 200
ligth = 201
medium = 202
high = 203

**Comment by infernalK** [comment]
Hi,
Do you need more informations ?

**Comment by afharo** [comment]
Not really, no. Thanks!

I just need to find and put some spare time together to get this done 😅

**Comment by infernalK** [comment]
Okay,
In case you need information or test something just ask I will be happy to help
