### ISSUE TITLE
all homebridge devices "no response" - one of two tokens wrong

### ISSUE THREAD

**Issue by nicoh88** [nicoh88/homebridge-xiaomi-roborock-vacuum#81]
Hi @afharo,

you know I'm not a programmer. Unfortunately, since you made the great changes, I no longer understand the code and cannot solve any problems. :-D

I have two roborocks in my `config.json`.
One of two tokens is wrong - since I reset the robot, due to a faulty firmware update. But I only get to read the token again the day after tomorrow.

**The problem is, however, that all other devices on the homebridge are no longer accessible.**

![IMG_2878](https://user-images.githubusercontent.com/264264/72242990-f5c26a80-35ea-11ea-96ef-b90f8b6d92f8.png)

Probably a bug?

```
[2020-1-13 9:41:28] [Staubsauger EG Flur] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
 (node:1597) UnhandledPromiseRejectionWarning: Error: Could not connect to device, token might be wrong
  at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/network.js:329:16
  at async XiaomiRoborockVacuum.initializeDevice (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:336:20)
  at async XiaomiRoborockVacuum.connect (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:404:7)
(node:1597) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Thank you

**Comment by afharo** [comment]
Let me have a look at it this evening or tomorrow (I'll be home alone) :)

**Comment by afharo** [comment]
So to be clear, in order to reproduce it. If I set a second instance of the robot in `config.json` with a wrong token, I will see all the devices connected via homebridge failing (not just the faulty device)?

**Comment by nicoh88** [comment]
> So to be clear, in order to reproduce it. If I set a second instance of the robot in `config.json` with a wrong token, I will see all the devices connected via homebridge failing (not just the faulty device)?

Exactly!
