### ISSUE TITLE
New token not working

### ISSUE THREAD

**Issue by kimme1024** [nicoh88/homebridge-xiaomi-roborock-vacuum#88]
I recently had to replace the LDS motor on my S5.
This caused my vacuum to be out for about 3 weeks.
Today I fixed everything but it couldn't connect to homebridge.
Homebridge gave the error mentioned in #81.
I retrieved a new token but I noticed that it was a lot longer. Nevertheless I changed it in the config.json.
Sadly I'm still getting the same error (#81).
Any ideas to fix this?

**Comment by kimme1024** [comment]
Getting this output btw:

`[2020-1-28 13:24:59] [Xiaomi Roborock S50] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
(node:64760) UnhandledPromiseRejectionWarning: Error: Could not connect to device, token might be wrong
    at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/network.js:329:16
(node:64760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by afharo** [comment]
Yes, that error handler was added to master. But was not published to NPM.

Maybe @nicoh88 can publish it?

**Comment by kimme1024** [comment]
> Yes, that error handler was added to master. But has not been published to NPM yet.
> Maybe @nicoh88 can publish it?
> 
> In the meanwhile, @kimme1024 you can try installing it from git, pointing to the master branch:
> https://docs.npmjs.com/cli/install
> 
> ```
> npm install <git remote url>:
> 
> Installs the package from the hosted git provider, cloning it with git. For a full git remote url, only that URL will be attempted.
> 
>     <protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]
> <protocol> is one of git, git+ssh, git+http, git+https, or git+file.
> 
> If #<commit-ish> is provided, it will be used to clone exactly that commit. If the commit-ish has the format #semver:<semver>, <semver> can be any valid semver range or exact version, and npm will look for any tags or refs matching that range in the remote repository, much as it would for a registry dependency. If neither #<commit-ish> or #semver:<semver> is specified, then the default branch of the repository is used.
> ```

Hi @afharo,

Thanks for the reply!

I'm not that familiar with what you're suggesting so could you give me the git remote url please?

**Comment by afharo** [comment]
Sure thing!
```
npm -g install git://git@github.com:nicoh88/homebridge-xiaomi-roborock-vacuum.git
```

**Comment by afharo** [comment]
But still, this will only solve the issue with crashing.
I'm still puzzled with the token issue. And it being longer.

**Comment by afharo** [comment]
> I'm still puzzled with the token issue. And it being longer.

Are you sure you decrypted it? https://python-miio.readthedocs.io/en/latest/discovery.html#extracting-tokens

**Comment by kimme1024** [comment]
@afharo is it normal that the update takes a long time to start?

I immediately get: `The authenticity of host 'github.com (140.82.118.3)' can't be established`
after which it starts the update but it doesn't do anything after that...

As for the token I've been following these steps as it's the thing I did the first time and the only way it seems to work with the devices I own.
https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md#ios-users

**Comment by afharo** [comment]
> I immediately get: The authenticity of host 'github.com (140.82.118.3)' can't be established
after which it starts the update but it doesn't do anything after that...

I think it's waiting for you to write "yes" :)

**Comment by kimme1024** [comment]
> > I immediately get: The authenticity of host 'github.com (140.82.118.3)' can't be established
> > after which it starts the update but it doesn't do anything after that...
> 
> I think it's waiting for you to write "yes" :)

after I've typed in yes this came up:
m ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/nicoh88/homebridge-xiaomi-roborock-vacuum.git
npm ERR! 
npm ERR! Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
npm ERR! Connection closed by 140.82.118.3 port 22
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128


As for the decryption I think I found the issue in the document I've attached. I was so stupid to have skipped the last step

**Comment by nicoh88** [comment]
Version 0.6.5 published:

- Feature: Add support for Roborock S5 Max
- Improve: Refresh the state every 30s to ensure miio is still properly connected
- Bugfix: Battery level
- Bugfix: UnhandledPromiseRejectionWarning on startup when it fails to connect

Install:

```
sudo su -
npm -g install homebridge-xiaomi-roborock-vacuum@latest
```

**Comment by afharo** [comment]
@nicoh88 to the rescue!! Thanks!!

**Comment by kimme1024** [comment]
@afharo @nicoh88 

Everything works again!
Thanks for the great support!
