### ISSUE TITLE
Roborock S5 new firmware, wrong fan speed

### ISSUE THREAD

**Issue by terriblefox** [nicoh88/homebridge-xiaomi-roborock-vacuum#89]
After the latest firmware upgrade it seems that the S5 also uses the 3rd gen fan speed index. getting this errors:

WAR changedSpeed | roborock.vacuum.s5 | Speed was changed to 102%, this speed is not supported
WAR changedSpeed | roborock.vacuum.s5 | Speed was changed to 104%, this speed is not supported

There are 5 modes of fan speed in the app. 
Gentle (this is optional)
Silent
Standard
Medium
Turbo

firmware 3.5.7_002008

**Comment by terriblefox** [comment]
I changed the profile in the index.js for S5 to gen3 and now it seems to work fine again.

INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 102% (Balanced), for HomeKit 60%

INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 104% (Max), for HomeKit 100%

perhaps a selection can be created....

**Comment by afharo** [comment]
Yes... I’m thinking we should expose this in the config so we can overwrite the defaults

**Comment by nicoh88** [comment]
Or an firmware-check, if is an roborock.vacuum.s5 and firmware higher or equal 2008 then ...

**Comment by afharo** [comment]
Absolutely: I was thinking of both options...
1. Add this new firmware check (as with any other new updates we'll need in the future).
2. Also provide a way to override the default behaviour (in all our iterations) so our advanced users can test and hack around until they find the nice spot. Then we can implement it to work like that by default. 

This way they can use the plugin without waiting for us to update it (although they can create PRs anyway but...) :)

**Comment by serbasan** [comment]
Hi. I have the new firmware and now the speeds don't work well. 
How can I change it? Will it be released in a new version? Many thanks for your work.
