### ISSUE TITLE
[REQUEST] Xiaomi Mijia STYJ02YM (Mop P)

### ISSUE THREAD

**Issue by Drun555** [nicoh88/homebridge-xiaomi-roborock-vacuum#90]
Hi! Mijia STYJ02YM was recently implemented in [python-miio](https://github.com/rytilahti/python-miio). Can I (we) ask for a support someday?

**Comment by nicoh88** [comment]
This `homebridge` Pluginsworks with [miio](https://github.com/aholstenson/miio), not [python-miio](https://github.com/rytilahti/python-miio).

[miio](https://github.com/aholstenson/miio) is no longer developed by the developer. We can only adjust rudimentary things. If the Vaccum works similarly to the S50, you can try whether the plugin works or what an error message comes up. But unfortunately we will no longer be able to support a "mopping" mode.
