### ISSUE TITLE
Log entries every 30 seconds

### ISSUE THREAD

**Issue by Soilman82** [nicoh88/homebridge-xiaomi-roborock-vacuum#94]
Hi, 

I'm not sure if this is normal and necessary or if this is a bug. Every 30 seconds I see the same log entries, like this:

[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF changedCharging | roborock.vacuum.s5 | Charging is active
[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 100%
[2020-1-31 16:03:41] [Xiaomi Roborock S50 Vaccum 2nd Generation] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 100% (Max), for HomeKit 100%

Why do I see these log entries (always the same) every 30 seconds? 

Kind regards 
Michael

**Comment by FlipMuc** [comment]
even though it is mentioned as a feature in the release note of the latest version, I agree that the amount it puts in the logs is pretty annoying

**Comment by Soilman82** [comment]
It would be nice if this can be switched on and off via config.json

**Comment by afharo** [comment]
In the PR above, I've changed the logic to only add those entries when the new value has actually been changed.

**Comment by Soilman82** [comment]
Thank you! Can’t wait for the next npm release. 😃

**Comment by nicoh88** [comment]
Fixed, waiting on version 0.6.6 or test the #master (0.6.6-dev) branch.

```
sudo su -
npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master

```

**Comment by costispavlou** [comment]
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 20:19:45] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:20:23] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:20:34] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:20:34] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:25:41] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:26:01] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:26:01] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:26:02] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:26:02] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 20:26:06] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%

version 0.6.8

**Comment by afharo** [comment]
@costispavlou it looks like something totally different to me.

The module logs each request (all of these are GET requests). Maybe you have an open Home app in any device checking the status every now and then?

These requests are not constant (so I wouldn’t assume it’s an automated stuff):
1. First batch: 20:19:45
2. Second batch: 20:20:23 (+38s)
3. Third batch: 20:25:41 (+5m 18s)?
4. Forth: 20:26:01 (+20s)
5. Fifth: 20:26:06 (+4s)

I bet if you enable the debug logging (run `homebridge -D`) you’ll see log entries like `GET /characteristic ...` before each of the batches.

**Comment by costispavlou** [comment]
Oh so you're telling me that every time I open home.app the plugin does it?

**Comment by costispavlou** [comment]
just opened the home.app now and it fired right up. 
no problem then. Thank you for your input

[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 21:20:40] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getBattery | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getCharging | roborock.vacuum.s5 | Charging is true (Status is charging)
[Homebridge] [2/15/2020, 21:20:43] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 21:39:29] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[Homebridge] [2/15/2020, 21:39:29] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[Homebridge] [2/15/2020, 21:39:29] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
[Homebridge] [2/15/2020, 21:39:29] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%

**Comment by afharo** [comment]
Yup. Not every single time (for some reason) some times the Home app decides it’s good enough with its own cached info 😅

But most times it request the status.

If it’s too annoying, maybe we can discuss adding a “silent” mode in the config that will avoid logging the INFO messages?

**Comment by costispavlou** [comment]
nuh. i only thought it was an error, hence posting.
looks good. thank you for your work.
